#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>
#
# authoring-projector.py — project stdlib/authoring-shapes-v0.1.yaml
# (the guided-edit shape registers SSOT: schema_shapes + armor_shapes)
# to every consumer surface. Values change in the YAML FIRST, then
# re-project. Sibling of starters-projector.py (same law, same exits).
#
#   TARGET 0 · in-repo      shape self-check (kebab ids unique · label/
#                           hint budgets · schema bodies open on
#                           `schema:` · armor bodies open on their key)
#                           PLUS the oracle proof — every body, grafted
#                           onto a minimal workflow (schema under an
#                           infer: · armor at task level), must validate
#                           against the conformance runner. Unproven
#                           shapes never project.
#   TARGET 1 · nika-vscode  src/core/authoringShapes.generated.ts
#
# Sibling resolution (env-overridable · missing sibling = skipped so a
# standalone spec clone projects nothing):
#   vscode · $NIKA_VSCODE_SRC · else <spec-root>/../vscode/repo/src ·
#            else <spec-root>/../../vscode/repo/src · else .../vscode/src
#
# Exit codes · 0 in-sync/written · 1 drift (--check) · 2 environment or
# schema error.

import json
import os
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("authoring-projector · pyyaml required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

SPEC_ROOT = Path(__file__).resolve().parent.parent
SHAPES_PATH = SPEC_ROOT / "stdlib" / "authoring-shapes-v0.1.yaml"

KEBAB_RE = re.compile(r"^[a-z][a-z0-9-]*$")
ARMOR_KEYS = ("retry", "on_error", "timeout")


def fail(msg: str, code: int = 2) -> None:
    print(f"authoring-projector · {msg}", file=sys.stderr)
    sys.exit(code)


def check_common(s: dict, seen: set) -> None:
    sid = s.get("id", "")
    if not KEBAB_RE.match(sid):
        fail(f"shape id {sid!r} is not kebab-case")
    if sid in seen:
        fail(f"shape id {sid!r} duplicated")
    seen.add(sid)
    if not s.get("label") or len(s["label"]) > 40:
        fail(f"{sid}: label missing or over the 40-char picker budget")
    if not s.get("hint") or len(s["hint"]) > 120:
        fail(f"{sid}: hint missing or over the 120-char detail budget")


def load_shapes() -> dict:
    if not SHAPES_PATH.exists():
        fail("stdlib/authoring-shapes-v0.1.yaml missing")
    data = yaml.safe_load(SHAPES_PATH.read_text())
    if data.get("authoring_version") != 1:
        fail("unknown authoring_version (want 1)")
    seen: set[str] = set()
    schema_shapes = data.get("schema_shapes", [])
    armor_shapes = data.get("armor_shapes", [])
    if not schema_shapes or not armor_shapes:
        fail("both schema_shapes and armor_shapes must be non-empty")
    for s in schema_shapes:
        check_common(s, seen)
        if not s.get("body", "").startswith("schema:"):
            fail(f"{s['id']}: schema body must open on `schema:`")
    for s in armor_shapes:
        check_common(s, seen)
        key = s.get("key")
        if key not in ARMOR_KEYS:
            fail(f"{s['id']}: key must be one of {ARMOR_KEYS}, got {key!r}")
        if not s.get("body", "").startswith(f"{key}:"):
            fail(f"{s['id']}: armor body must open on `{key}:`")
    return data


def scaffold_schema(shape_id: str, body: str) -> str:
    """Graft a schema block under a minimal infer: — the editor gesture."""
    out = [
        "nika: v1",
        f"workflow: {shape_id}",
        'description: "shape proof — generated by authoring-projector"',
        "model: mock/echo",
        "tasks:",
        "  - id: probe",
        "    infer:",
        '      prompt: "probe"',
    ]
    out.extend(("      " + line) if line.strip() else line
               for line in body.rstrip("\n").split("\n"))
    return "\n".join(out) + "\n"


def scaffold_armor(shape_id: str, body: str) -> str:
    """Graft an armor block at task level on a minimal exec: task."""
    out = [
        "nika: v1",
        f"workflow: {shape_id}",
        'description: "shape proof — generated by authoring-projector"',
        "model: mock/echo",
        "tasks:",
        "  - id: probe",
    ]
    out.extend(("    " + line) if line.strip() else line
               for line in body.rstrip("\n").split("\n"))
    out.append("    exec:")
    out.append('      command: ["true"]')
    return "\n".join(out) + "\n"


def prove(data: dict) -> None:
    """TARGET 0 oracle proof — every shape validates, or nothing projects."""
    sys.path.insert(0, str(SPEC_ROOT / "conformance"))
    try:
        from runner import load_canon, load_schema, validate_text  # noqa: PLC0415
    except ImportError as e:
        fail(f"conformance runner unavailable ({e}) — run from a full spec checkout")
    validator = load_schema()
    canon = load_canon()
    bad = 0
    probes = [(s["id"], scaffold_schema(s["id"], s["body"])) for s in data["schema_shapes"]]
    probes += [(s["id"], scaffold_armor(s["id"], s["body"])) for s in data["armor_shapes"]]
    for sid, text in probes:
        verdict = validate_text(text, validator, canon)
        if not verdict["valid"]:
            bad += 1
            for err in verdict["errors"]:
                print(f"authoring-projector · {sid} FAILS the oracle · "
                      f"{err.get('code', err.get('namespace'))} · {err['detail']}",
                      file=sys.stderr)
    if bad:
        fail(f"{bad} shape(s) fail the conformance oracle — fix the SSOT, never the consumer")


def emit_ts(data: dict) -> str:
    j = lambda v: json.dumps(v, ensure_ascii=False)  # noqa: E731
    lines = [
        "// authoringShapes.generated.ts — AUTO-GENERATED by nika-spec",
        "// scripts/authoring-projector.py from stdlib/authoring-shapes-v0.1.yaml",
        "// (the guided-edit shape registers SSOT: schema + armor). DO NOT EDIT —",
        "// values change SPEC-FIRST. Regenerate: python3 scripts/authoring-projector.py --write",
        "// Drift gate: --check (spec CI + consumer gates).",
        "",
        "export interface SchemaShape {",
        "  readonly id: string;",
        "  /** The picker row (≤ 40 chars). */",
        "  readonly label: string;",
        "  /** The picker detail — teaches the why (≤ 120 chars). */",
        "  readonly hint: string;",
        "  /** The schema block, unindented (first line is `schema:`) — consumers re-indent. */",
        "  readonly body: string;",
        "}",
        "",
        "export interface ArmorShape {",
        "  readonly id: string;",
        "  /** The task-level key the shape writes. */",
        "  readonly key: 'retry' | 'on_error' | 'timeout';",
        "  readonly label: string;",
        "  readonly hint: string;",
        "  /** The block, unindented (first line names the key) — consumers re-indent. */",
        "  readonly body: string;",
        "}",
        "",
        "export const NIKA_SCHEMA_SHAPES: readonly SchemaShape[] = [",
    ]
    for s in data["schema_shapes"]:
        lines.append("  {")
        lines.append(f"    id: {j(s['id'])},")
        lines.append(f"    label: {j(s['label'])},")
        lines.append(f"    hint: {j(s['hint'])},")
        lines.append(f"    body: {j(s['body'])},")
        lines.append("  },")
    lines.append("] as const;")
    lines.append("")
    lines.append("export const NIKA_ARMOR_SHAPES: readonly ArmorShape[] = [")
    for s in data["armor_shapes"]:
        lines.append("  {")
        lines.append(f"    id: {j(s['id'])},")
        lines.append(f"    key: {j(s['key'])},")
        lines.append(f"    label: {j(s['label'])},")
        lines.append(f"    hint: {j(s['hint'])},")
        lines.append(f"    body: {j(s['body'])},")
        lines.append("  },")
    lines.append("] as const;")
    lines.append("")
    return "\n".join(lines)


def resolve_vscode_src() -> Path | None:
    env = os.environ.get("NIKA_VSCODE_SRC")
    if env:
        p = Path(env)
        return p if p.is_dir() else None
    for cand in ("../vscode/repo/src", "../../vscode/repo/src", "../vscode/src"):
        p = (SPEC_ROOT / cand).resolve()
        if p.is_dir():
            return p
    return None


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode not in ("--check", "--write"):
        fail("usage: authoring-projector.py [--check | --write]")
    data = load_shapes()
    prove(data)
    ts = emit_ts(data)

    drift = False
    vscode_src = resolve_vscode_src()
    if vscode_src is None:
        print("authoring-projector · vscode sibling absent — TARGET 1 skipped")
    else:
        target = vscode_src / "core" / "authoringShapes.generated.ts"
        current = target.read_text() if target.exists() else None
        if mode == "--write":
            if current != ts:
                target.write_text(ts)
                print(f"authoring-projector · wrote {target}")
            else:
                print(f"authoring-projector · {target} already in sync")
        elif current != ts:
            drift = True
            print(f"authoring-projector · DRIFT · {target} "
                  f"({'missing' if current is None else 'differs'}) — re-run with --write",
                  file=sys.stderr)
    if drift:
        return 1
    print("authoring-projector · all targets in sync" if mode == "--check"
          else "authoring-projector · projection complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
