#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>
#
# docs-canon-snippet.py — project canon.yaml (the Nika language SSOT) into
# the Mintlify docs snippet `snippets/_canon.mdx` (supernovae-st/nika-docs).
#
# THE LAW (projection-by-default) · canon.yaml is THE source · the docs
# snippet is a PROJECTION · docs pages import { CANON } and interpolate
# {CANON.providers} etc. — they NEVER hand-type a volatile language fact.
# Sister of the engine's scripts/mintlify-snapshot.sh (which projects
# ENGINE facts into _status-snapshot.mdx as STATUS). Two SSOTs · two
# snippets · spec facts ⊥ engine facts (mirrors the Apache/AGPL split).
#
# Target path resolution (priority order):
#   1. $NIKA_DOCS_SNIPPETS env var (explicit override)
#   2. <spec-root>/../docs/snippets/   (monorepo sibling submodule)
#
# Usage:
#   python3 scripts/docs-canon-snippet.py --write   # regenerate the snippet
#   python3 scripts/docs-canon-snippet.py --check   # drift gate (exit 1 on diff)
#
# Exit codes · 0 in-sync/written · 1 drift (--check) · 2 environment or
# intra-canon error (counts != len(items) · missing files · bad schema).

import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("docs-canon-snippet · pyyaml required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

SPEC_ROOT = Path(__file__).resolve().parent.parent
SUPPORTED_SCHEMA = 1


def resolve_snippet_path() -> Path:
    env = os.environ.get("NIKA_DOCS_SNIPPETS")
    if env:
        return Path(env) / "_canon.mdx"
    sibling = SPEC_ROOT.parent / "docs" / "snippets"
    if sibling.is_dir():
        return sibling / "_canon.mdx"
    print(
        "docs-canon-snippet · cannot resolve docs snippets dir · "
        "set NIKA_DOCS_SNIPPETS or run from the monorepo layout",
        file=sys.stderr,
    )
    sys.exit(2)


def load_canon() -> dict:
    canon_path = SPEC_ROOT / "canon.yaml"
    if not canon_path.is_file():
        print(f"docs-canon-snippet · canon.yaml not found at {canon_path}", file=sys.stderr)
        sys.exit(2)
    with canon_path.open() as f:
        canon = yaml.safe_load(f)
    if canon.get("schema_version") != SUPPORTED_SCHEMA:
        print(
            f"docs-canon-snippet · unsupported schema_version "
            f"{canon.get('schema_version')!r} (supported: {SUPPORTED_SCHEMA}) · "
            "upgrade this projector explicitly",
            file=sys.stderr,
        )
        sys.exit(2)
    return canon


def self_check(canon: dict) -> None:
    """The intra-canon law · every category's count == len(items)."""

    def die(cat: str, count: int, actual: int) -> None:
        print(
            f"docs-canon-snippet · intra-canon drift · {cat} count: {count} "
            f"!= len(items) {actual} · fix canon.yaml first",
            file=sys.stderr,
        )
        sys.exit(2)

    for cat in ("verbs", "builtins", "extract_modes", "error_namespaces", "pillars"):
        count = canon[cat]["count"]
        actual = len(canon[cat]["items"])
        if count != actual:
            die(cat, count, actual)
    p = canon["providers"]
    actual = sum(len(v) for v in p["items"].values())
    if p["count"] != actual:
        die("providers", p["count"], actual)


def js_str_list(items: list) -> str:
    return "[" + ", ".join(f'"{i}"' for i in items) + "]"


def render(canon: dict) -> str:
    verbs = canon["verbs"]["items"]
    verb_names = [v["name"] for v in verbs]
    builtins = canon["builtins"]["items"]
    providers = canon["providers"]["items"]
    cloud, local, test = providers["cloud"], providers["local"], providers["test"]
    extract = canon["extract_modes"]["items"]
    namespaces = canon["error_namespaces"]["items"]

    return f"""{{/* _canon.mdx — AUTO-GENERATED by scripts/docs-canon-snippet.py (nika-spec repo)
    from canon.yaml — the Nika language single source of truth.
    DO NOT EDIT · regenerate: python3 scripts/docs-canon-snippet.py --write
    Drift gate: --check (wired into the SuperNovae run-all audit). */}}

export const CANON = {{
  schemaVersion: {canon["schema_version"]},
  verbs: {canon["verbs"]["count"]},
  verbNames: {js_str_list(verb_names)},
  builtins: {canon["builtins"]["count"]},
  builtinNames: {js_str_list(builtins)},
  providers: {canon["providers"]["count"]},
  providersCloud: {len(cloud)},
  providersLocal: {len(local)},
  providersTest: {len(test)},
  providerIdsCloud: {js_str_list(cloud)},
  providerIdsLocal: {js_str_list(local)},
  providerIdsTest: {js_str_list(test)},
  extractModes: {canon["extract_modes"]["count"]},
  extractModeNames: {js_str_list(extract)},
  errorNamespaces: {canon["error_namespaces"]["count"]},
  errorNamespaceNames: {js_str_list(namespaces)},
  pillars: {canon["pillars"]["count"]},
}};
"""


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode not in ("--write", "--check"):
        print(f"docs-canon-snippet · unknown mode {mode!r} (--write | --check)", file=sys.stderr)
        return 2

    canon = load_canon()
    self_check(canon)
    rendered = render(canon)
    target = resolve_snippet_path()

    if mode == "--write":
        target.write_text(rendered)
        c = canon
        print(
            f"✓ wrote {target}\n"
            f"  verbs={c['verbs']['count']} builtins={c['builtins']['count']} "
            f"providers={c['providers']['count']} extract_modes={c['extract_modes']['count']} "
            f"error_namespaces={c['error_namespaces']['count']}"
        )
        return 0

    # --check · drift gate
    if not target.is_file():
        print(f"docs-canon-snippet · DRIFT · {target} absent · run --write", file=sys.stderr)
        return 1
    if target.read_text() != rendered:
        print(
            f"docs-canon-snippet · DRIFT · {target} differs from canon.yaml "
            "projection · run --write",
            file=sys.stderr,
        )
        return 1
    print("✓ _canon.mdx in sync with canon.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
