#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Gate-v2 observation matrix — model-authored, engine-proven.

The COMPLETE admission matrix of 03 §gate algebra v2: producer terminal
state {success · failure · skipped · cancelled} × consumer edge form
{with-value · with-status · with-error · after:succeeded · after:failed ·
after:skipped · after:terminal · when-true · when-false · no-edge} =
40 cells. Every cell is a PERMANENT fixture:

- 35 cells are runtime observations → `conformance/tests/runtime/gates/`
  (input.nika.yaml + run.json + expected-run.json). Expected statuses come
  from `reference/semantics.py` — the model DEFINES the outcome, this
  script never hand-writes one.
- 5 cells are STATICALLY DEAD (03 §static liveness): the edge's pass-set
  excludes every reachable producer state → `conformance/tests/deep/`
  fixtures expecting NIKA-DAG-006 (check-only tier · the check refuses
  them before any run — that refusal IS the cell's semantics).
- plus one NIKA-DAG-007 vocabulary fixture (the bad-status-literal class
  that guards the observation half of the matrix).

usage:
  python3 scripts/gen-gate-matrix.py --write        # (re)generate fixtures
  python3 scripts/gen-gate-matrix.py --check        # drift gate (temp + diff)
  python3 scripts/gen-gate-matrix.py --prove BIN    # run the 35 at a binary
"""

from __future__ import annotations

import argparse
import filecmp
import json
import pathlib
import shutil
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE / "reference"))
from semantics import evaluate_text  # noqa: E402

STATES = ["success", "failure", "skipped", "cancelled"]
FORMS = [
    "with-value", "with-status", "with-error",
    "after-succeeded", "after-failed", "after-skipped", "after-terminal",
    "when-true", "when-false", "no-edge",
]
# Statically-dead cells (03 §static liveness): the producer's reachable
# state set never intersects the edge's pass-set — NIKA-DAG-006 territory.
DEAD_CELLS = {
    ("success", "after-skipped"),
    ("failure", "after-skipped"),
    ("cancelled", "after-skipped"),
    ("skipped", "after-succeeded"),
    ("skipped", "after-failed"),
}

RUNTIME_DIR = HERE / "conformance" / "tests" / "runtime" / "gates"
DEEP_DIR = HERE / "conformance" / "tests" / "deep"


def producer_yaml(state: str) -> str:
    """seed → p scaffold; p settles exactly `state` at runtime while keeping
    every OTHER edge form statically live (03 §static liveness)."""
    seed_cmd = '["false"]' if state == "cancelled" else '["true"]'
    lines = [
        "  seed:",
        f"    exec: {{ command: {seed_cmd} }}",
        "  p:",
        "    after: { seed: succeeded }",
    ]
    if state == "skipped":
        lines.append("    when: false")
    p_cmd = '["false"]' if state == "failure" else '["echo", "the producer speaks"]'
    lines.append(f"    exec: {{ command: {p_cmd} }}")
    return "\n".join(lines)


def consumer_yaml(form: str) -> str:
    body = {
        "with-value": [
            '    with: { v: "${{ tasks.p.output }}" }',
            '    exec: { command: ["echo", "got ${{ with.v }}"] }',
        ],
        "with-status": [
            '    with: { s: "${{ tasks.p.status }}" }',
            '    exec: { command: ["echo", "p was ${{ with.s }}"] }',
        ],
        "with-error": [
            '    with: { e: "${{ tasks.p.error }}" }',
            '    exec: { command: ["echo", "observation carried"] }',
        ],
        "after-succeeded": [
            "    after: { p: succeeded }",
            '    exec: { command: ["echo", "strict path"] }',
        ],
        "after-failed": [
            "    after: { p: failed }",
            '    exec: { command: ["echo", "failure path"] }',
        ],
        "after-skipped": [
            "    after: { p: skipped }",
            '    exec: { command: ["echo", "skip path"] }',
        ],
        "after-terminal": [
            "    after: { p: terminal }",
            '    exec: { command: ["echo", "always path"] }',
        ],
        "when-true": [
            "    when: true",
            '    exec: { command: ["echo", "independent"] }',
        ],
        "when-false": [
            "    when: false",
            '    exec: { command: ["echo", "never spoken"] }',
        ],
        "no-edge": [
            '    exec: { command: ["echo", "independent"] }',
        ],
    }[form]
    return "\n".join(["  c:"] + body)


def cell_workflow(state: str, form: str) -> str:
    return "\n".join([
        "# SPDX-License-Identifier: Apache-2.0",
        f"# gate-v2 matrix cell · producer settles {state} × consumer {form}",
        "# generated by scripts/gen-gate-matrix.py — edit the generator, not this",
        "nika: v1",
        "workflow:",
        f"  id: gate-{state}-x-{form}",
        "tasks:",
        producer_yaml(state),
        consumer_yaml(form),
        "",
    ])


# Deterministic side observations the pass-set semantics PIN (asserted on
# top of the model's statuses — the terminal-observation contract in bytes).
OUTPUT_CONTAINS = {
    ("success", "with-status"): ("c", "p was success"),
    ("failure", "with-status"): ("c", "p was failure"),
    ("skipped", "with-status"): ("c", "p was skipped"),
    ("cancelled", "with-status"): ("c", "p was cancelled"),
    ("success", "with-value"): ("c", "got the producer speaks"),
}


def expected_run(state: str, form: str, text: str) -> dict:
    model = evaluate_text(text)
    statuses = {tid: v["status"] for tid, v in model.items()}
    workflow_state = "failure" if any(
        v["status"] == "failure" and not v["recovered"] for v in model.values()
    ) else "success"
    tasks: dict[str, dict] = {tid: {"status": st} for tid, st in sorted(statuses.items())}
    hit = OUTPUT_CONTAINS.get((state, form))
    if hit and statuses.get(hit[0]) == "success":
        tasks[hit[0]]["output_contains"] = hit[1]
    return {
        "workflow_state": workflow_state,
        "tasks": tasks,
        "note": f"gate-v2 matrix · {state} × {form} · statuses authored by "
                "reference/semantics.py (the model defines · the engine follows)",
    }


def dead_cell_fixture(state: str, form: str) -> tuple[str, dict]:
    text = cell_workflow(state, form)
    expected = {
        "valid": False,
        "errors": [{"code": "NIKA-DAG-006", "category": "validation_error"}],
        "note": f"03-dag.md §static liveness · gate-v2 matrix cell {state} × "
                f"{form}: the edge's pass-set can never admit — the producer's "
                "reachable states exclude it · statically dead, refused before "
                "any run.",
    }
    return text, expected


VOCAB_FIXTURE = """\
# SPDX-License-Identifier: Apache-2.0
# gate-v2 observation guard · status literal outside the vocabulary
# generated by scripts/gen-gate-matrix.py — edit the generator, not this
nika: v1
workflow:
  id: gate-bad-status-literal
tasks:
  p:
    exec: { command: ["true"] }
  c:
    with: { s: "${{ tasks.p.status }}" }
    when: "${{ with.s != 'failed' }}"
    exec: { command: ["echo", "lives but lies"] }
"""

VOCAB_EXPECTED = {
    "valid": False,
    "errors": [{"code": "NIKA-DAG-007", "category": "validation_error"}],
    "note": "03-dag.md §static liveness · 'failed' is not a status (the "
            "vocabulary is success · failure · skipped · cancelled) — == "
            "never matches, != always holds · did-you-mean fix: 'failure'.",
}

# Deep-tier numbering continues the hand fixtures (022 is the last one) —
# gate liveness is a CHECK-layer surface (reach.rs), so the fixtures live
# in the deep tier the engine verdicts against the real `check()`.
DEEP_CELLS = [
    ("023-dead-after-skipped-on-success-producer", "success", "after-skipped"),
    ("024-dead-after-skipped-on-failure-producer", "failure", "after-skipped"),
    ("025-dead-after-skipped-on-cancelled-producer", "cancelled", "after-skipped"),
    ("026-dead-after-succeeded-on-skipped-producer", "skipped", "after-succeeded"),
    ("027-dead-after-failed-on-skipped-producer", "skipped", "after-failed"),
]
DEEP_VOCAB = "028-bad-status-literal-vocabulary"


def readme(cells: list[tuple[str, str, str]]) -> str:
    rows = ["# The gate-v2 observation matrix (generated)", "",
            "40 cells · producer state × consumer edge form. 35 run (this",
            "directory) · 5 are statically dead (NIKA-DAG-006 · they live in",
            "`../../deep/023-027`) · vocabulary guard at `../../deep/028`.",
            "Regenerate: `python3 scripts/gen-gate-matrix.py --write` ·",
            "drift gate: `--check` · engine proof: `--prove <nika-cli>`.",
            "", "| producer \\ form | " + " | ".join(FORMS) + " |",
            "|---|" + "---|" * len(FORMS)]
    by_cell = {(s, f): name for name, s, f in cells}
    for s in STATES:
        row = [f"| `{s}`"]
        for f in FORMS:
            if (s, f) in DEAD_CELLS:
                row.append("`DAG-006` (core)")
            else:
                row.append(f"[{by_cell[(s, f)].split('-', 1)[0]}]({by_cell[(s, f)]}/)")
        rows.append(" | ".join(row) + " |")
    rows.append("")
    return "\n".join(rows)


def generate(root: pathlib.Path) -> list[tuple[str, str, str]]:
    """Write every fixture under `root` (a spec checkout layout). Returns
    the runtime cell list [(dirname, state, form)]."""
    gates = root / "conformance" / "tests" / "runtime" / "gates"
    deep = root / "conformance" / "tests" / "deep"
    gates.mkdir(parents=True, exist_ok=True)
    deep.mkdir(parents=True, exist_ok=True)

    cells: list[tuple[str, str, str]] = []
    n = 10
    for form in FORMS:
        for state in STATES:
            if (state, form) in DEAD_CELLS:
                continue
            name = f"{n:03d}-{state}-x-{form}"
            d = gates / name
            d.mkdir(exist_ok=True)
            text = cell_workflow(state, form)
            (d / "input.nika.yaml").write_text(text)
            (d / "run.json").write_text('{"vars": {}}\n')
            (d / "expected-run.json").write_text(
                json.dumps(expected_run(state, form, text), indent=2) + "\n")
            cells.append((name, state, form))
            n += 1
    (gates / "MATRIX.md").write_text(readme(cells))

    for name, state, form in DEEP_CELLS:
        d = deep / name
        d.mkdir(exist_ok=True)
        text, expected = dead_cell_fixture(state, form)
        (d / "input.yaml").write_text(text)
        (d / "expected.json").write_text(json.dumps(expected, indent=2) + "\n")
    d = deep / DEEP_VOCAB
    d.mkdir(exist_ok=True)
    (d / "input.yaml").write_text(VOCAB_FIXTURE)
    (d / "expected.json").write_text(json.dumps(VOCAB_EXPECTED, indent=2) + "\n")
    return cells


def check_drift() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_root = pathlib.Path(tmp)
        generate(tmp_root)
        bad = 0
        for rel_root, committed in (
            (tmp_root / "conformance" / "tests" / "runtime" / "gates", RUNTIME_DIR),
            (tmp_root / "conformance" / "tests" / "deep", DEEP_DIR),
        ):
            for path in sorted(rel_root.rglob("*")):
                if path.is_dir():
                    continue
                target = committed / path.relative_to(rel_root)
                if not target.exists() or not filecmp.cmp(path, target, shallow=False):
                    print(f"DRIFT {target.relative_to(HERE)}")
                    bad += 1
        print("gate-matrix --check:", "clean" if bad == 0 else f"{bad} drifted")
        return 0 if bad == 0 else 1


def prove(binary: str) -> int:
    sys.path.insert(0, str(HERE / "reference"))
    from differential import run_engine  # noqa: E402
    bad = 0
    total = 0
    for d in sorted(RUNTIME_DIR.iterdir()):
        wf = d / "input.nika.yaml"
        if not wf.exists():
            continue
        total += 1
        text = wf.read_text()
        expected = json.loads((d / "expected-run.json").read_text())
        engine = run_engine(binary, text)
        got = {tid: v["status"] for tid, v in engine.items()}
        want = {tid: v["status"] for tid, v in expected["tasks"].items()}
        if got != want:
            bad += 1
            print(f"DIVERGENT {d.name}: model={want} engine={got}")
    print(f"gate-matrix --prove: {total - bad}/{total} cells agree · bin={binary}")
    return 0 if bad == 0 else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--prove", metavar="BIN")
    args = ap.parse_args()
    if args.write:
        cells = generate(HERE)
        print(f"gate-matrix --write: {len(cells)} runtime cells · "
              f"{len(DEEP_CELLS)} static (DAG-006) · 1 vocabulary (DAG-007)")
        return 0
    if args.check:
        return check_drift()
    return prove(args.prove)


if __name__ == "__main__":
    raise SystemExit(main())
