#!/usr/bin/env python3
# llms-projector.py · generates llms.txt + llms-full.txt from the spec sources
# License · Apache-2.0 (part of the Nika spec)
#
# Projection-by-default (same architecture as canon-projectors.py): the spec
# chapters + stdlib contracts are the SOURCE · the two llms files are
# PROJECTIONS regenerated here · drift caught with --check at commit time.
#
# Format · https://llmstxt.org (H1 → blockquote summary → prose → H2 link
# sections → ## Optional). llms-full.txt = the whole spec concatenated into
# one markdown file (the Mintlify-era convention for inference-time reading
# by coding agents).
#
# Usage ·
#   python3 scripts/llms-projector.py            # regenerate both files
#   python3 scripts/llms-projector.py --check    # exit 1 if out of sync

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("llms-projector · pyyaml required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
RAW = "https://raw.githubusercontent.com/supernovae-st/nika-spec/main"

# Ordered projection sources for llms-full.txt · the normative reading path.
FULL_ORDER = [
    "README.md",
    "QUICKSTART.md",
    "spec/00-overview.md",
    "spec/01-envelope.md",
    "spec/02-verbs.md",
    "spec/03-dag.md",
    "spec/04-variables.md",
    "spec/05-errors.md",
    "spec/06-stdlib-contract.md",
    "spec/07-conformance.md",
    "spec/08-out-of-scope.md",
    "spec/09-types.md",
    "stdlib/builtins-v0.1.md",
    "stdlib/providers-v0.1.md",
    "stdlib/extract-modes-v0.1.md",
    "registry/registry-v0.1.md",
]

def load_counts() -> dict:
    """Counts interpolated into llms.txt come from canon.yaml — never
    hand-typed here. (The 2026-07-06 audit caught this template carrying
    24 builtins / 14 providers while every marker surface was already
    reprojected · the template was the last hand-written count site.)"""
    with (ROOT / "canon.yaml").open(encoding="utf-8") as f:
        canon = yaml.safe_load(f)
    return {
        "builtins": canon["builtins"]["count"],
        "providers": canon["providers"]["count"],
        "extract_modes": canon["extract_modes"]["count"],
        "error_namespaces": canon["error_namespaces"]["count"],
    }


def build_llms_txt(c: dict) -> str:
    return f"""# Nika

> Intent as Code · a workflow language for AI. Four verbs (`infer` · `exec` ·
> `invoke` · `agent`), a YAML envelope (`nika: v1` · forever), a closed
> stdlib ({c["builtins"]} builtins · {c["providers"]} providers), and a conformance suite. Apache-2.0
> spec · AGPL-3.0 reference engine in Rust (single static binary).

Workflow files are `*.nika.yaml`. The JSON Schema gives any editor
autocomplete + validation via a `yaml-language-server` modeline:
`{RAW}/schemas/workflow.schema.json`

## Spec

- [Overview]({RAW}/spec/00-overview.md): what Nika is · the five design pillars
- [Envelope]({RAW}/spec/01-envelope.md): the `nika: v1` marker · top-level shape
- [Verbs]({RAW}/spec/02-verbs.md): the four closed verbs · infer · exec · invoke · agent
- [DAG]({RAW}/spec/03-dag.md): the two doors — with: data edges · after: control · gate v2 · fan-out
- [Variables]({RAW}/spec/04-variables.md): the five namespaces · CEL + jq expressions
- [Errors]({RAW}/spec/05-errors.md): the NIKA-XXX code contract · {c["error_namespaces"]} namespaces
- [Stdlib contract]({RAW}/spec/06-stdlib-contract.md): {c["builtins"]} builtins · {c["providers"]} providers · {c["extract_modes"]} extract modes
- [Conformance]({RAW}/spec/07-conformance.md): three levels · the fixture suite · editor tooling
- [Out of scope]({RAW}/spec/08-out-of-scope.md): what Nika deliberately does not do
- [Types]({RAW}/spec/09-types.md): the decidable type core · types: · returns: · decode:

## Reference

- [Canonical registry]({RAW}/canon.yaml): the machine-readable single source of truth
- [JSON Schema]({RAW}/schemas/workflow.schema.json): editor autocomplete + validation
- [Builtins]({RAW}/stdlib/builtins-v0.1.md): the {c["builtins"]} canonical builtins
- [Providers]({RAW}/stdlib/providers-v0.1.md): the {c["providers"]}-provider catalog (local-first)
- [Quickstart]({RAW}/QUICKSTART.md): author + check + run a first workflow

## Optional

- [Extract modes]({RAW}/stdlib/extract-modes-v0.1.md): the {c["extract_modes"]} `nika:fetch` extract modes
- [Registry contract]({RAW}/registry/registry-v0.1.md): how artifacts are shared — entries, trust model, advisories
- [Changelog]({RAW}/CHANGELOG.md): spec evolution log
- [Reference engine](https://github.com/supernovae-st/nika): Rust · AGPL-3.0 · `brew install supernovae-st/tap/nika`
"""


def build_full() -> str:
    parts = [
        "<!-- llms-full.txt · GENERATED by scripts/llms-projector.py · do not"
        " hand-edit -->\n<!-- The whole Nika spec concatenated for"
        " inference-time reading. -->\n"
    ]
    for rel in FULL_ORDER:
        p = ROOT / rel
        if not p.is_file():
            print(f"llms-projector: missing source {rel}", file=sys.stderr)
            sys.exit(2)
        parts.append(f"\n\n<!-- ═══ {rel} ═══ -->\n\n")
        parts.append(p.read_text(encoding="utf-8").strip())
    return "".join(parts) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    targets = {
        ROOT / "llms.txt": build_llms_txt(load_counts()),
        ROOT / "llms-full.txt": build_full(),
    }
    dirty = []
    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            if check:
                dirty.append(path.name)
            else:
                path.write_text(content, encoding="utf-8")
                print(f"✓ wrote {path.name}")
    if check:
        if dirty:
            print(f"✗ out of sync: {', '.join(dirty)} · run scripts/llms-projector.py")
            return 1
        print("✓ llms files in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
