#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>
#
# showcase-projector.py — project examples/showcase/*.nika.yaml (the
# single source for every public workflow example) into the consumer
# surfaces. Sister of canon-projectors.py (canon.yaml → counts) · same
# law (projection-by-default) · same modes (--write | --check).
#
#   TARGET 1 · nika-docs   examples/<slug>.mdx     managed yaml block
#              (between `{/* showcase:begin <file> */}` and
#               `{/* showcase:end */}` markers · prose around the block
#               stays hand-crafted · the YAML inside is machine-owned)
#   TARGET 2 · nika.sh     src/sections/usecases-yaml.generated.ts
#              (slug → lean yaml string · fully generated module)
#
# « Lean » rendering · the SPDX header, the yaml-language-server hint
# and the leading comment banner are stripped for display (the prose
# explains; the file teaches) — body comments are kept.
#
# Target path resolution (priority order):
#   docs    · $NIKA_DOCS_ROOT    · else <spec-root>/../docs/
#   website · $NIKA_WEBSITE_SRC  · else <spec-root>/../website/src/
#   (a missing sibling is SKIPPED · standalone spec clones project nothing)
#
# Exit codes · 0 in-sync/written · 1 drift (--check) · 2 environment error.

import os
import re
import sys
from pathlib import Path

SPEC_ROOT = Path(__file__).resolve().parent.parent
SHOWCASE = SPEC_ROOT / "examples" / "showcase"

BEGIN = re.compile(r"\{/\* showcase:begin ([a-z0-9-]+\.nika\.yaml) \*/\}")
END = "{/* showcase:end */}"


def lean(yaml_text: str) -> str:
    """Strip the comment banner (everything before the `nika: v1` line)."""
    lines = yaml_text.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("nika:"):
            return "\n".join(lines[i:]).rstrip() + "\n"
    print("showcase-projector · no `nika:` envelope line found", file=sys.stderr)
    sys.exit(2)


def load_showcase() -> dict[str, str]:
    if not SHOWCASE.is_dir():
        print(f"showcase-projector · {SHOWCASE} missing", file=sys.stderr)
        sys.exit(2)
    files = sorted(SHOWCASE.glob("*.nika.yaml"))
    if not files:
        print("showcase-projector · no showcase files", file=sys.stderr)
        sys.exit(2)
    return {f.name: lean(f.read_text()) for f in files}


def render_ts(workflows: dict[str, str]) -> str:
    entries = []
    for name, body in workflows.items():
        slug = name.removesuffix(".nika.yaml")
        escaped = body.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        entries.append(f"  '{slug}': `{escaped}`,")
    joined = "\n".join(entries)
    return (
        "// usecases-yaml.generated.ts — AUTO-GENERATED by\n"
        "// scripts/showcase-projector.py (nika-spec repo) from\n"
        "// examples/showcase/*.nika.yaml — the single source for every\n"
        "// public workflow example. DO NOT EDIT · regenerate:\n"
        "//   python3 scripts/showcase-projector.py --write\n"
        "// Drift gate: --check (wired into the SuperNovae run-all audit).\n\n"
        "export const SHOWCASE_YAML: Record<string, string> = {\n"
        f"{joined}\n"
        "}\n"
    )


def project_docs_page(page: Path, workflows: dict[str, str], write: bool) -> bool:
    """Rewrite every managed yaml block in one docs page. True = in sync."""
    text = page.read_text()
    out, pos, dirty = [], 0, False
    for m in BEGIN.finditer(text):
        fname = m.group(1)
        if fname not in workflows:
            print(f"showcase-projector · {page.name} references unknown {fname}",
                  file=sys.stderr)
            sys.exit(2)
        end_idx = text.find(END, m.end())
        if end_idx == -1:
            print(f"showcase-projector · {page.name} · unterminated block {fname}",
                  file=sys.stderr)
            sys.exit(2)
        managed = f"\n```yaml {fname}\n{workflows[fname]}```\n"
        current = text[m.end():end_idx]
        if current != managed:
            dirty = True
        out.append(text[pos:m.end()])
        out.append(managed)
        pos = end_idx
    out.append(text[pos:])
    if dirty and write:
        page.write_text("".join(out))
    return not dirty


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode not in ("--write", "--check"):
        print("showcase-projector · mode --write | --check", file=sys.stderr)
        return 2
    write = mode == "--write"
    workflows = load_showcase()
    rc = 0

    # TARGET 1 · docs managed blocks
    docs_env = os.environ.get("NIKA_DOCS_ROOT")
    docs_root = Path(docs_env) if docs_env else SPEC_ROOT.parent / "docs"
    pages_dir = docs_root / "examples"
    if pages_dir.is_dir():
        for page in sorted(pages_dir.glob("*.mdx")):
            in_sync = project_docs_page(page, workflows, write)
            if in_sync:
                continue
            if write:
                print(f"✓ wrote docs · {page.name}")
            else:
                print(f"showcase-projector · DRIFT · docs/{page.name} · run --write",
                      file=sys.stderr)
                rc = 1
    else:
        print("· docs examples/ absent · skipped")

    # TARGET 2 · website generated module
    web_env = os.environ.get("NIKA_WEBSITE_SRC")
    web_src = Path(web_env) if web_env else SPEC_ROOT.parent / "website" / "src"
    if web_src.is_dir():
        target = web_src / "sections" / "usecases-yaml.generated.ts"
        rendered = render_ts(workflows)
        if write:
            target.write_text(rendered)
            print(f"✓ wrote website · {target}")
        elif not target.is_file() or target.read_text() != rendered:
            print("showcase-projector · DRIFT · website usecases-yaml.generated.ts · run --write",
                  file=sys.stderr)
            rc = 1
        else:
            print("✓ website in sync (usecases-yaml.generated.ts)")
    else:
        print("· website src/ absent · skipped")

    if rc == 0 and not write:
        print(f"✓ showcase projection in sync · {len(workflows)} workflows")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
