#!/usr/bin/env python3
"""ssot-compiler v0 · C0 SANDBOX (estate · zero repo mutation)

Contract source: design-pack-pre1/01_STRUCTURED_LAW_SCHEMA.md §6 + PRE1_C0_SCOPE.md §3
+ PRE1_C0_FIRST_72H_PLAN.md T+24h. Sandbox instance: parses canon/laws/*.yaml, validates
every law entry against schemas/law.schema.json (SEALED, consumed as-is), validates the
12 registry documents against schemas/registries.schema.json, resolves law refs into the
seeded registries, emits ONE deterministic projection (projections/laws-index.json,
stable sort by law id, canonical JSON, NFC, LF) plus canon/ssot.lock (leaf digests only,
digest-dag layer 1, own digest DETACHED in canon/ssot.lock.sha256 per PAA-006).

Modes
  write (default)   regenerate projection + lock + sidecar, print digests
  --check           regenerate in memory, byte-compare against disk, never write
  --check-canon     v0.2 (canon-flip · MIG-canon-yaml) · parity gate registries <-> canon.yaml
                    ("jamais deux vérités" · SSOT-1). For every IMPORTED section the gate
                    verifies count == len(items) AND the item set == the registry row set
                    (scoped per section: surface kind=verb/namespace spellings · builtins
                    "nika:"+name ids · templates ids · error_codes as a subset of the
                    diagnostics ids with registry-ahead rows reported · mcp.protocol_versions
                    via the bijective id transform · outcome_transitions.classes vs the
                    sealed outcome_class enum · the derivable half of error_namespaces).
                    Sections WITHOUT a sealed registry home are DECLARED skips mirroring
                    canon/EXCEPTIONS.md (the §18 exception ledger) — the two lists must
                    stay in lockstep. Read-only · zero network · deterministic output.
                    SINCE THE FLIP (SSOT-1 §23) the gate additionally verifies canon.yaml
                    carries the GENERATED header AND equals its own --emit-canon
                    regeneration byte-for-byte — a manual edit of a generated surface
                    is rc 5, never silent.
  --emit-canon      the flip (SSOT-1 §21-23 · MIG-canon-yaml completes) · regenerate
                    canon.yaml: the gated surfaces are RE-DERIVED from the registries
                    (counts by len(items) · verbs/namespaces from surface spellings +
                    the notes-carried « … » verbatim semantics · builtins/templates from
                    row ids · error_codes fields from the import-c0 rows (condition ==
                    failure text · category/transient greppables in notes) · the 2 §27
                    seed rows NIKA-AGENT-001/002 stay template-carried per FINDING CF-12 ·
                    mcp.protocol_versions via the bijective id transform (latest = max) ·
                    outcome_transitions.classes from the sealed enum) — the 16 ledger
                    sections (canon/EXCEPTIONS.md) + every prose comment + the authored
                    item SEQUENCE are carried VERBATIM from the current file (they stay
                    authored · the ledger says so). A GENERATED header goes on top with
                    the body sha256 (own digest detached per PAA-006 — the header hashes
                    the body, never itself). Deterministic: regenerating twice from the
                    same commit produces the same bytes. Writes canon.yaml · prints digest.

Exit codes
  0  OK (write done, --check byte-identical, --check-canon full parity, or
     --emit-canon written)
  1  --check drift (any regenerated byte differs from disk)
  2  schema/reference refusal (law or registry row invalid, unresolved ref, dup law id,
     or --emit-canon cannot regenerate: orphan canon item · underivable row field ·
     unknown top-level section · corrupted header)
  3  input profile violation (R11 gate: anchor, alias, merge key, duplicate key,
     custom tag, non-string key, NaN/Infinity in a canon source file)
  4  usage or environment error
  5  --check-canon divergence (every diverging section + exact item names listed ·
     incl. the flip gate: GENERATED header missing or bytes differing from the
     regeneration)

Determinism: sorted file iteration, sorted JSON keys, NFC, LF, no timestamps, no
absolute paths in outputs. Zero network: jsonschema validates with local schemas only.

Dependencies: python3 stdlib + jsonschema + PyYAML. FINDING-09: the sandbox rule said
stdlib+jsonschema only, but the mandated inputs are YAML; PyYAML (already the spec
reference-model parser, see spec repo reference/semantics.py) is used for INPUT parsing
only, wrapped in the R11-enforcing loader below (the dogfood gate: our own SSOT sources
must satisfy the very profile the pilot laws import).
"""

import hashlib
import json
import re
import sys
import unicodedata
from pathlib import Path

try:
    import yaml
    import jsonschema
except ImportError as exc:  # pragma: no cover
    print(f"ssot-compiler: missing dependency: {exc}", file=sys.stderr)
    sys.exit(4)

GENERATOR_IDENTITY = "ssot-compiler"
GENERATOR_VERSION = "0.2.0-sandbox"

# The 13 SSOT components (machine/registries-inventory.json, consumed as-is).
REGISTRY_COMPONENTS = {
    "surface": "canon/surface.yaml",
    "grammar": "canon/grammar.yaml",
    "types": "canon/types.yaml",
    "diagnostics": "canon/diagnostics",  # registry-modular (dir)
    "builtins": "canon/builtins.yaml",
    "features": "canon/features.yaml",
    "templates": "canon/templates/registry.yaml",
    "snippets": "canon/snippets/registry.yaml",
    "conformance": "canon/conformance.yaml",
    "tombstones": "canon/tombstones.yaml",
    "projections": "canon/projections.yaml",
    "migrations": "canon/migrations.yaml",
}
LAWS_DIR = "canon/laws"
PROJECTION_PATH = "projections/laws-index.json"
LOCK_PATH = "canon/ssot.lock"
LOCK_SIDECAR_PATH = "canon/ssot.lock.sha256"

YAML_CORE_TAGS = {
    "tag:yaml.org,2002:str", "tag:yaml.org,2002:int", "tag:yaml.org,2002:float",
    "tag:yaml.org,2002:bool", "tag:yaml.org,2002:null", "tag:yaml.org,2002:map",
    "tag:yaml.org,2002:seq",
}


class ProfileViolation(Exception):
    """R11 gate: the canon source violates the Nika YAML profile."""


class RefusedError(Exception):
    """Schema or reference refusal (exit 2)."""


def _mark(mark):
    return f"line {mark.line + 1}, column {mark.column + 1}" if mark else "unknown position"


def profile_scan_events(text, relpath):
    """R11 event-level gate: anchors, aliases, merge keys, custom tags (points 1, 3, 13)."""
    for event in yaml.parse(text):
        if isinstance(event, yaml.events.AliasEvent):
            raise ProfileViolation(
                f"{relpath}: YAML alias (*{event.anchor}) at {_mark(event.start_mark)} · "
                "R11 point 1: the Nika profile forbids aliases")
        anchor = getattr(event, "anchor", None)
        if anchor is not None:
            raise ProfileViolation(
                f"{relpath}: YAML anchor (&{anchor}) at {_mark(event.start_mark)} · "
                "R11 points 1+3: forbidden even when never referenced")
        if isinstance(event, yaml.events.ScalarEvent):
            if event.style is None and event.value == "<<":
                raise ProfileViolation(
                    f"{relpath}: YAML merge key (<<) at {_mark(event.start_mark)} · "
                    "R11 point 1: the Nika profile forbids merge keys")
            if event.tag is not None and event.tag not in YAML_CORE_TAGS:
                raise ProfileViolation(
                    f"{relpath}: custom tag {event.tag} at {_mark(event.start_mark)} · "
                    "R11 point 13: only the YAML core schema is admitted")


class ProfileLoader(yaml.SafeLoader):
    """R11 construction-level gate: duplicate keys, non-string keys, NaN/Infinity."""

    def construct_mapping(self, node, deep=False):
        seen = set()
        for key_node, _value in node.value:
            key = self.construct_object(key_node, deep=True)
            if not isinstance(key, str):
                raise ProfileViolation(
                    f"non-string mapping key {key!r} at {_mark(key_node.start_mark)} · "
                    "R11 point 13: mapping keys are strings")
            if key in seen:
                raise ProfileViolation(
                    f"duplicate mapping key {key!r} at {_mark(key_node.start_mark)} · "
                    "R11 points 5+13: duplicate keys are refused")
            seen.add(key)
        return super().construct_mapping(node, deep=deep)


def _construct_profile_float(loader, node):
    value = yaml.SafeLoader.construct_yaml_float(loader, node)
    if value != value or value in (float("inf"), float("-inf")):
        raise ProfileViolation(
            f"non-finite float {node.value!r} at {_mark(node.start_mark)} · "
            "R11 point 13: NaN/Infinity are refused")
    return value


ProfileLoader.add_constructor("tag:yaml.org,2002:float", _construct_profile_float)


def load_profile_text(text, relpath):
    if text.startswith("\ufeff"):
        raise ProfileViolation(f"{relpath}: BOM present · R11 point 13 (unicode contract)")
    profile_scan_events(text, relpath)
    try:
        doc = yaml.load(text, Loader=ProfileLoader)
    except ProfileViolation as exc:
        raise ProfileViolation(f"{relpath}: {exc}") from None
    except yaml.YAMLError as exc:
        raise RefusedError(f"{relpath}: YAML parse error: {exc}") from None
    return doc


def load_profile_yaml(path, root):
    return load_profile_text(path.read_text(encoding="utf-8"), path.relative_to(root).as_posix())


def canonical_bytes(obj):
    """Canonical JSON: sorted keys, minimal separators, NFC, LF, trailing newline."""
    text = json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return (unicodedata.normalize("NFC", text) + "\n").encode("utf-8")


def sha256_bytes(data):
    return "sha256:" + hashlib.sha256(data).hexdigest()


def load_schema(root, name):
    path = root / "schemas" / name
    if not path.is_file():
        raise RefusedError(f"missing sealed schema: schemas/{name}")
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def validate_or_collect(validator, instance, label, errors):
    for err in sorted(validator.iter_errors(instance), key=lambda e: list(e.absolute_path)):
        pointer = "/" + "/".join(str(p) for p in err.absolute_path)
        errors.append(f"{label} · at {pointer or '/'} · {err.message}")


def collect_law_files(root):
    laws_dir = root / LAWS_DIR
    if not laws_dir.is_dir():
        raise RefusedError(f"missing laws component dir: {LAWS_DIR}")
    return sorted(p for p in laws_dir.glob("*.yaml") if p.is_file())


def extract_laws(doc, relpath):
    """Accept the two documented shapes: bare list, or mapping with a `laws` list."""
    if isinstance(doc, list):
        return doc
    if isinstance(doc, dict) and isinstance(doc.get("laws"), list):
        return doc["laws"]
    raise RefusedError(
        f"{relpath}: unsupported laws document shape (expected a list of entries "
        "or a mapping with a `laws` list)")


def collect_registry_docs(root):
    docs = {}
    for component, rel in REGISTRY_COMPONENTS.items():
        path = root / rel
        if component == "diagnostics":
            if not path.is_dir():
                raise RefusedError(f"missing registry-modular dir: {rel}")
            files = sorted(p for p in path.glob("*.yaml") if p.is_file())
            if not files:
                raise RefusedError(f"empty registry-modular dir: {rel}")
            docs[component] = [(p, load_profile_yaml(p, root)) for p in files]
        else:
            if not path.is_file():
                raise RefusedError(f"missing registry file: {rel}")
            docs[component] = [(path, load_profile_yaml(path, root))]
    return docs


def registry_row_ids(docs):
    ids = {}
    for component, filedocs in docs.items():
        rows = []
        for _path, doc in filedocs:
            rows.extend(doc.get(component) or [])
        ids[component] = {row.get("id") for row in rows if isinstance(row, dict)}
    return ids


def iter_typed_refs(law):
    for ref in law.get("inputs", []):
        yield "inputs", ref
    for ref in law.get("judgment", {}).get("generated_facts", []):
        yield "judgment.generated_facts", ref
    subject = law.get("domain_payload", {}).get("subject")
    if isinstance(subject, dict):
        yield "domain_payload.subject", subject


def resolve_refs(laws, row_ids, errors):
    """ir refs are runtime/IR symbols (unresolvable in canon by design, like the sealed
    examples' required_capabilities). Every other registry ref must hit a seeded row."""
    for law in laws:
        law_id = law.get("id", "<no-id>")
        for where, ref in iter_typed_refs(law):
            registry = ref.get("registry")
            rid = ref.get("id")
            if registry in (None, "ir", "laws"):
                continue
            if registry not in row_ids:
                errors.append(f"{law_id} · {where} · unknown registry {registry!r}")
                continue
            if rid not in row_ids[registry]:
                errors.append(
                    f"{law_id} · {where} · unresolved ref {registry}:{rid} "
                    "(no seeded row · SSOT-1 §12 orphan)")


# ---------------------------------------------------------------- check-canon (v0.2)

CANON_PATH = "canon.yaml"

# Declared skips · MUST mirror canon/EXCEPTIONS.md (SSOT-1 §18 exception ledger).
# A canon.yaml section neither imported below nor listed here = drift (rc 5).
CANON_EXCEPTIONS = {
    "counts": "derived by this gate (count == len(items) verified per section) · never copied",
    "providers": "needs registry home ruling (C1) · see canon/EXCEPTIONS.md",
    "extract_modes": "needs registry home ruling (C1) · see canon/EXCEPTIONS.md",
    "error_categories": "no category field in the sealed diagnosticRow · carried in row notes · ruling owed C1 (CF-10)",
    "outcome_transitions.legal": "table-13 registry home owed C1 · kernel-ahead causes = FINDINGS CF-07/CF-08",
    "outcome_transitions.payload": "table-13 registry home owed C1 (rides the same ruling as .legal)",
    "pillars": "studio vocabulary · stays authored per operator reco",
    "lifecycle_product": "studio vocabulary · stays authored per operator reco",
    "lifecycle_decision": "studio vocabulary · stays authored per operator reco",
    "lifecycle_risk": "studio vocabulary · stays authored per operator reco",
    "diamond_layers": "studio vocabulary · stays authored per operator reco",
    "steal_pattern_tiers": "studio vocabulary · stays authored per operator reco",
    "severity": "studio vocabulary · stays authored per operator reco",
    "mcp.tools": "engine-verified projection (crates/nika-mcp/src/tools.rs) · features home ruling owed C1",
    "canonical_phrasing": "one-voice phrasing registry · canon/snippets home ruling owed C1",
    "schema_version": "canon.yaml projection marker · SURVIVES the flip verbatim (reader contract: "
                      "canon-projectors.py exits 2 on unknown version · monorepo derive gates) · "
                      "retirement rides the C1 projector cascade (CF-13)",
}

# canon.yaml namespaces declared code-free at v0.1 (canon.yaml + spec/05-errors.md
# concrete table both carry zero codes for them · FINDING CF-09 · ledger row).
CANON_DECLARED_EMPTY_NAMESPACES = {"NIKA-IMPL", "NIKA-PROVIDER"}


def _canon_item_names(section):
    """Item spellings for a canon.yaml section (dict items carry name/code keys)."""
    items = section["items"]
    if isinstance(items, dict):  # providers-style nested groups
        return [x for group in items.values() for x in group]
    out = []
    for it in items:
        if isinstance(it, dict):
            out.append(it.get("name") or it.get("code"))
        else:
            out.append(it)
    return out


def _fmt_set(values, cap=12):
    values = sorted(values)
    shown = " ".join(values[:cap])
    return shown + (f" (+{len(values) - cap} more)" if len(values) > cap else "")


def check_canon(root):
    """Parity gate registries <-> canon.yaml (read-only). Returns (lines, divergences)."""
    canon_file = root / CANON_PATH
    if not canon_file.is_file():
        raise RefusedError(f"missing canon source: {CANON_PATH}")
    canon = load_profile_yaml(canon_file, root)
    registries_schema = load_schema(root, "registries.schema.json")
    docs = collect_registry_docs(root)

    def rows(component):
        out = []
        for _path, doc in docs[component]:
            out.extend(doc.get(component) or [])
        return out

    lines, divergences = [], []

    def gate(section, canon_names, row_names, subset_only=False, extra_note=None):
        canon_set, row_set = set(canon_names), set(row_names)
        declared = canon.get(section) if "." not in section else None
        count = declared.get("count") if isinstance(declared, dict) else None
        if count is not None and count != len(canon_names):
            divergences.append(
                f"{section}: canon count {count} != len(items) {len(canon_names)} (intra-canon self-check)")
        missing = canon_set - row_set
        if missing:
            divergences.append(f"{section}: canon items with NO registry row: {_fmt_set(missing)}")
        if not subset_only:
            extra = row_set - canon_set
            if extra:
                divergences.append(f"{section}: registry rows with NO canon item: {_fmt_set(extra)}")
        if not missing and (subset_only or row_set == canon_set):
            lines.append(f"PARITY {section} · canon {len(canon_set)} == rows {len(row_set & canon_set)}"
                         + (f" · {extra_note}" if extra_note else ""))

    # counts block · every counts.<key> must equal its section's count/len (derived, never copied)
    counts = canon.get("counts", {})
    for key, value in sorted(counts.items()):
        if key == "mcp_tools":
            section, names = "mcp.tools", _canon_item_names(canon["mcp"]["tools"])
        elif key == "mcp_protocol_versions":
            section, names = "mcp.protocol_versions", _canon_item_names(canon["mcp"]["protocol_versions"])
        else:
            section, names = key, _canon_item_names(canon[key])
        if value != len(names):
            divergences.append(f"counts.{key}: {value} != len({section}.items) {len(names)}")
    lines.append(f"COUNTS · {len(counts)} keys verified against len(items) (derived · never copied)")

    # verbs + namespaces -> canon/surface.yaml (scoped by row kind · spelling carries the word)
    surface_rows = rows("surface")
    gate("verbs", _canon_item_names(canon["verbs"]),
         [r["spelling"] for r in surface_rows if r.get("kind") == "verb"])
    gate("namespaces", _canon_item_names(canon["namespaces"]),
         [r["spelling"] for r in surface_rows if r.get("kind") == "namespace"])

    # builtins -> canon/builtins.yaml (row id = "nika:" + item · duplicate row ids = a second truth)
    builtin_ids = [r["id"] for r in rows("builtins")]
    dupes = {i for i in builtin_ids if builtin_ids.count(i) > 1}
    if dupes:
        divergences.append(f"builtins: duplicate registry rows for {_fmt_set(dupes)} (a second truth)")
    gate("builtins", [f"nika:{n}" for n in _canon_item_names(canon["builtins"])], builtin_ids)

    # templates -> canon/templates/registry.yaml (row id = item)
    gate("templates", _canon_item_names(canon["templates"]), [r["id"] for r in rows("templates")])

    # error_codes -> canon/diagnostics (subset · kernel-born rows may run AHEAD of the canon projection)
    diag_rows = rows("diagnostics")
    diag_ids = {r["id"] for r in diag_rows}
    canon_code_names = _canon_item_names(canon["error_codes"])
    ahead = diag_ids - set(canon_code_names)
    gate("error_codes", canon_code_names, diag_ids, subset_only=True,
         extra_note=(f"registry-ahead rows (not yet in canon.yaml · CF-05): {_fmt_set(ahead)}" if ahead else None))

    # error_namespaces · derivable half GATED: every canon-code row's namespace must be a canon namespace
    canon_ns = set(_canon_item_names(canon["error_namespaces"]))
    derived_ns = {"NIKA-" + r["namespace"] for r in diag_rows if r["id"] in set(canon_code_names)}
    outside = derived_ns - canon_ns
    if outside:
        divergences.append(f"error_namespaces: row namespaces outside the canon set: {_fmt_set(outside)}")
    uncovered = canon_ns - derived_ns
    undeclared_empty = uncovered - CANON_DECLARED_EMPTY_NAMESPACES
    if undeclared_empty:
        divergences.append(
            f"error_namespaces: canon namespaces with zero rows and NOT declared empty (CF-09 ledger): "
            f"{_fmt_set(undeclared_empty)}")
    if not outside and not undeclared_empty:
        lines.append(f"PARITY error_namespaces · derived {len(derived_ns)}/{len(canon_ns)} · declared-empty "
                     f"(ledger CF-09): {_fmt_set(uncovered & CANON_DECLARED_EMPTY_NAMESPACES)}")

    # mcp.protocol_versions -> canon/features.yaml (bijective id transform · dashes -> underscores)
    expected_feats = {"mcp.protocol." + v.replace("-", "_")
                      for v in _canon_item_names(canon["mcp"]["protocol_versions"])}
    actual_feats = {r["id"] for r in rows("features") if r["id"].startswith("mcp.protocol.")}
    gate("mcp.protocol_versions", expected_feats, actual_feats)

    # outcome_transitions.classes vs the SEALED outcome_class enum (one class table · terminal never a class)
    classes = canon["outcome_transitions"]["classes"]
    enum_classes = registries_schema["$defs"]["diagnosticRow"]["properties"]["outcome_class"]["enum"]
    if set(classes) != set(enum_classes):
        divergences.append(
            f"outcome_transitions.classes: canon {sorted(classes)} != sealed outcome_class enum {sorted(enum_classes)}")
    else:
        lines.append(f"PARITY outcome_transitions.classes · canon == sealed enum ({len(classes)} classes)")
    for table in ("legal", "payload"):
        keys = set(canon["outcome_transitions"][table])
        if keys != set(classes):
            divergences.append(f"outcome_transitions.{table}: keys {sorted(keys)} != classes {sorted(classes)}")

    for section in sorted(CANON_EXCEPTIONS):
        lines.append(f"SKIP {section} · exception ledger (canon/EXCEPTIONS.md) · {CANON_EXCEPTIONS[section]}")

    # The flip gate (SSOT-1 §23) · since --emit-canon shipped, canon.yaml IS a
    # generated projection: the GENERATED header must be present and the file must
    # equal its own regeneration byte-for-byte. A manual edit of a generated
    # surface (or a registry moving without re-emission) = rc 5, never silent.
    # The 16 authored ledger sections are carried verbatim by the emitter —
    # editing THOSE stays legal and passes this gate.
    canon_bytes = canon_file.read_bytes()
    try:
        header, _body = split_canon_header(canon_bytes.decode("utf-8"))
        if header is None:
            divergences.append(
                "canon.yaml: GENERATED header missing — canon.yaml is a generated "
                "projection since the flip (SSOT-1 §23) · run --emit-canon")
        if emit_canon_bytes(root) != canon_bytes:
            divergences.append(
                "canon.yaml: bytes differ from the --emit-canon regeneration — manual "
                "edit of a generated surface, or the registries moved without "
                "re-emission · edit the registries, then run --emit-canon")
        elif header is not None:
            lines.append(
                "GENERATED canon.yaml == its own regeneration · byte-identical · header "
                "present (SSOT-1 §23 · manual edits of generated surfaces make CI red)")
    except RefusedError as exc:
        divergences.append(f"canon.yaml: not regenerable — {exc}")

    return lines, divergences



# ---------------------------------------------------------------- emit-canon (the flip)

CANON_HEADER_END = "# ---- end generated header (SSOT-1 §21-23 · the canon flip · C0)"

# The 21 canon.yaml top-level sections · gated surfaces + ledger rows. A section
# outside this set is neither generated nor declared-authored — the emitter refuses
# (SSOT-1 §29: nothing skipped silently) and --check-canon reports the divergence.
CANON_TOP_KEYS = {
    "schema_version", "counts", "outcome_transitions", "verbs", "namespaces",
    "builtins", "providers", "extract_modes", "templates", "error_namespaces",
    "error_categories", "error_codes", "pillars", "lifecycle_product",
    "lifecycle_decision", "lifecycle_risk", "diamond_layers", "steal_pattern_tiers",
    "severity", "mcp", "canonical_phrasing",
}

# FINDING CF-12 · the 2 SSOT-1 §27 seed rows (byte-untouched at the canon-flip
# import per the diagnostics $comment) are law-minted (LAW-OUTCOME-0403/0402 ·
# causes budget_exhausted/deadline_exceeded) and do NOT carry the canon.yaml v0.1
# projection fields (condition == failure verbatim · category/transient greppables).
# Their canon.yaml item lines stay AUTHORED (template-carried) until the C1
# diagnostics minting unifies them · membership stays gated (subset check) ·
# declared in canon/EXCEPTIONS.md findings register, never silent.
SEED_CARRIED_CODES = {"NIKA-AGENT-001", "NIKA-AGENT-002"}

CANON_TOP_KEY_RE = re.compile(r"^([a-z_]+):")
CANON_COUNTS_LINE_RE = re.compile(r"^  ([a-z_]+): \d+$")
CANON_SECTION_COUNT_RE = re.compile(r"^(\s+)count: \d+$")
CANON_CODE_ITEM_RE = re.compile(r"^    - \{ code: ([A-Z0-9-]+), ")


def _dq(value, label):
    """Render a derived string in the canon double-quoted flow style (refuse what
    the style cannot carry — mint an escaping rule explicitly before widening)."""
    if not isinstance(value, str) or any(c in value for c in ('"', "\\", "\n")):
        raise RefusedError(
            f"{label}: value {value!r} not representable in the canon double-quoted "
            "flow style (double quote · backslash · newline) — mint the escaping rule first")
    return f'"{value}"'


def split_canon_header(text):
    """(header_or_None, body_text) · header = the leading '# GENERATED' comment
    block through the end-sentinel line inclusive. Pre-flip files have none."""
    if not text.startswith("# GENERATED"):
        return None, text
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if line == CANON_HEADER_END:
            return "\n".join(lines[: i + 1]) + "\n", "\n".join(lines[i + 1:])
    raise RefusedError(
        "canon.yaml: GENERATED opener present but the end-of-header sentinel line is "
        f"missing (expected: {CANON_HEADER_END!r})")


def render_canon_header(body):
    """The GENERATED marker block (SSOT-1 §23). Hashes the BODY, never itself —
    own digest detached per PAA-006 (a self-including hash cannot exist)."""
    digest = hashlib.sha256(body).hexdigest()
    lines = [
        "# GENERATED · canon.yaml is a generated projection since the C0 flip — manual",
        "# edits of a generated surface make CI red (ssot-compiler --check-canon · rc=5:",
        "# the gate re-emits from the registries and byte-compares this file).",
        f"# generated-by: {GENERATOR_IDENTITY} {GENERATOR_VERSION} (scripts/ssot-compiler.py)",
        "# sources: canon/surface.yaml · canon/builtins.yaml · canon/templates/registry.yaml ·",
        "#   canon/diagnostics/ · canon/features.yaml · schemas/registries.schema.json (the",
        "#   sealed outcome_class enum) · the 16 ledger sections (canon/EXCEPTIONS.md ·",
        "#   SSOT-1 §18) stay AUTHORED and are carried verbatim — editing those is legal.",
        "# regenerate: python3 scripts/ssot-compiler.py --emit-canon",
        f"# body-sha256: {digest}",
        "#   (digest of every byte below the end-of-header line · detached self-hash per PAA-006)",
        CANON_HEADER_END,
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def derive_generated(root):
    """Everything --emit-canon re-derives from the registries + the sealed schema."""
    docs = collect_registry_docs(root)
    registries_schema = load_schema(root, "registries.schema.json")

    def rows(component):
        out = []
        for _path, doc in docs[component]:
            out.extend(doc.get(component) or [])
        return out

    verbs, namespaces = [], []
    for r in rows("surface"):
        kind = r.get("kind")
        if kind == "verb":
            m = re.search(r"verbs semantic verbatim: « (.+?) »", r.get("notes", ""))
            if not m:
                raise RefusedError(
                    f"surface row {r.get('id')}: verb semantic not derivable — notes must "
                    "carry `canon.yaml verbs semantic verbatim: « … »` (import-c0 contract)")
            verbs.append((r["spelling"], m.group(1)))
        elif kind == "namespace":
            namespaces.append(r["spelling"])

    builtins = []
    for r in rows("builtins"):
        rid = r.get("id", "")
        if not rid.startswith("nika:"):
            raise RefusedError(f"builtins row {rid!r}: id must carry the nika: prefix")
        builtins.append(rid[len("nika:"):])

    templates = [r["id"] for r in rows("templates")]

    diagnostics = {}
    for r in rows("diagnostics"):
        notes = r.get("notes", "")
        mcat = re.search(r"· category: ([a-z_]+) ·", notes)
        mtr = re.search(r"· transient: (false|engine-assessed) \(", notes)
        diagnostics[r["id"]] = {
            "category": mcat.group(1) if mcat else None,
            "transient": mtr.group(1) if mtr else None,
            "failure": r.get("condition"),
        }

    protocol_versions = [
        r["id"][len("mcp.protocol."):].replace("_", "-")
        for r in rows("features") if r.get("id", "").startswith("mcp.protocol.")
    ]

    classes = list(
        registries_schema["$defs"]["diagnosticRow"]["properties"]["outcome_class"]["enum"])

    return {
        "verbs": verbs, "namespaces": namespaces, "builtins": builtins,
        "templates": templates, "diagnostics": diagnostics,
        "protocol_versions": protocol_versions, "classes": classes,
    }


def _rw_simple_items(seg, rendered_items, section, indent="    "):
    """Derive the section count: by len(items) + replace the contiguous item block
    after `items:` with the registry-derived render. Prose lines pass verbatim."""
    out, i, replaced = [], 0, False
    while i < len(seg):
        line = seg[i]
        m = CANON_SECTION_COUNT_RE.match(line)
        if m:
            out.append(f"{m.group(1)}count: {len(rendered_items)}")
            i += 1
            continue
        if re.match(r"^\s+items:$", line) and not replaced:
            out.append(line)
            i += 1
            while i < len(seg) and seg[i].startswith(indent + "- "):
                i += 1
            out.extend(indent + "- " + item for item in rendered_items)
            replaced = True
            continue
        out.append(line)
        i += 1
    if not replaced:
        raise RefusedError(f"{section}: items: line not found (canon.yaml structure moved)")
    return out


def _rw_error_codes(seg, diag_rows):
    """error_codes · fields re-rendered from the diagnostics rows (condition ==
    failure verbatim · category/transient from the import-c0 note greppables) ·
    the item SEQUENCE + the retired-code comment blocks stay template-carried
    (authored presentation · order is not registry-derivable: the registry seeds
    lead with the §27/YAML rows) · the 2 seed-carried codes per CF-12."""
    item_count = sum(1 for line in seg if CANON_CODE_ITEM_RE.match(line))
    out = []
    for line in seg:
        if CANON_SECTION_COUNT_RE.match(line):
            out.append(f"  count: {item_count}")
            continue
        m = CANON_CODE_ITEM_RE.match(line)
        if not m:
            out.append(line)
            continue
        code = m.group(1)
        if code in SEED_CARRIED_CODES:
            out.append(line)
            continue
        row = diag_rows.get(code)
        if row is None:
            raise RefusedError(
                f"error_codes item {code}: no diagnostics registry row "
                "(SSOT-1 §12 orphan · cannot regenerate a code the registry does not carry)")
        cat, transient, failure = row["category"], row["transient"], row["failure"]
        if not (cat and transient and failure):
            raise RefusedError(
                f"error_codes item {code}: projection fields not derivable from the row "
                "(category/transient note greppables · condition) — import-c0 contract")
        out.append(
            f"    - {{ code: {code}, category: {cat}, "
            f"transient: {_dq(transient, code + '.transient')}, "
            f"failure: {_dq(failure, code + '.failure')} }}")
    return out, item_count


def _rw_mcp(seg, protocol_versions):
    """mcp · tools subsection stays authored (ledger row) · protocol_versions is
    generated: count by len · latest = max (ISO dates order lexicographically) ·
    items from the features rows via the bijective id transform."""
    out, i, in_pv, replaced = [], 0, False, False
    while i < len(seg):
        line = seg[i]
        if re.match(r"^  [a-z_]+:$", line):
            in_pv = line == "  protocol_versions:"
            out.append(line)
            i += 1
            continue
        if in_pv:
            if re.match(r"^    count: \d+$", line):
                out.append(f"    count: {len(protocol_versions)}")
                i += 1
                continue
            if re.match(r'^    latest: "', line):
                out.append(f"    latest: {_dq(max(protocol_versions), 'mcp.protocol_versions.latest')}")
                i += 1
                continue
            if line == "    items:" and not replaced:
                out.append(line)
                i += 1
                while i < len(seg) and seg[i].startswith("      - "):
                    i += 1
                out.extend(
                    f"      - {_dq(v, 'mcp.protocol_versions item')}" for v in protocol_versions)
                replaced = True
                continue
        out.append(line)
        i += 1
    if not replaced:
        raise RefusedError("mcp.protocol_versions: items: line not found (canon.yaml structure moved)")
    return out


def _rw_outcome(seg, classes):
    out, done = [], False
    for line in seg:
        if line.startswith("  classes: ["):
            out.append("  classes: [" + ", ".join(classes) + "]")
            done = True
        else:
            out.append(line)
    if not done:
        raise RefusedError("outcome_transitions.classes: line not found (canon.yaml structure moved)")
    return out


def emit_canon_body(root):
    """Regenerate the canon.yaml BODY: gated surfaces re-derived from the registries ·
    the 16 ledger sections + every prose comment carried verbatim from the current
    file (SSOT-1 §18: they stay authored). Returns bytes (LF · trailing newline)."""
    canon_file = root / CANON_PATH
    if not canon_file.is_file():
        raise RefusedError(f"missing canon source: {CANON_PATH}")
    text = canon_file.read_text(encoding="utf-8")
    _header, body_text = split_canon_header(text)
    if not body_text.endswith("\n"):
        raise RefusedError("canon.yaml: body must end with a trailing newline (LF contract)")
    canon = load_profile_text(text, CANON_PATH)
    derived = derive_generated(root)

    lines = body_text.split("\n")
    keys = [(idx, m.group(1)) for idx, line in enumerate(lines)
            if (m := CANON_TOP_KEY_RE.match(line))]
    if not keys:
        raise RefusedError("canon.yaml: no top-level sections found")
    spans, names = {}, []
    for pos, (idx, key) in enumerate(keys):
        if key not in CANON_TOP_KEYS:
            raise RefusedError(
                f"canon.yaml: unknown top-level section {key!r} — neither a gated surface "
                "nor a canon/EXCEPTIONS.md ledger row (SSOT-1 §29: nothing skipped silently)")
        if key in spans:
            raise RefusedError(f"canon.yaml: duplicate top-level section {key!r}")
        end = keys[pos + 1][0] if pos + 1 < len(keys) else len(lines)
        spans[key] = (idx, end)
        names.append(key)
    for required in ("counts", "outcome_transitions", "verbs", "namespaces", "builtins",
                     "templates", "error_codes", "mcp"):
        if required not in spans:
            raise RefusedError(f"canon.yaml: gated section {required!r} missing")

    def span_lines(key):
        s, e = spans[key]
        return lines[s:e]

    # error_codes first (its emitted item count feeds the counts block)
    diag = derived["diagnostics"]
    seg_error_codes, error_codes_len = _rw_error_codes(span_lines("error_codes"), diag)

    verb_names = [n for n, _s in derived["verbs"]]
    if not verb_names:
        raise RefusedError("surface registry: no kind=verb rows (cannot derive verbs)")
    pad = max(len(n) for n in verb_names) + 2
    verb_items = [
        f"{{ name: {(n + ','):<{pad}}semantic: {_dq(s, 'verb ' + n)} }}"
        for n, s in derived["verbs"]]

    generated_lens = {
        "verbs": len(derived["verbs"]),
        "namespaces": len(derived["namespaces"]),
        "builtins": len(derived["builtins"]),
        "templates": len(derived["templates"]),
        "error_codes": error_codes_len,
        "mcp_protocol_versions": len(derived["protocol_versions"]),
    }

    def counts_value(key):
        if key in generated_lens:
            return generated_lens[key]
        if key == "mcp_tools":
            return len(_canon_item_names(canon["mcp"]["tools"]))
        if key not in canon or not isinstance(canon[key], dict) or "items" not in canon[key]:
            raise RefusedError(f"counts.{key}: no matching canon section items to derive from")
        return len(_canon_item_names(canon[key]))

    def rw_counts(seg):
        out = []
        for line in seg:
            m = CANON_COUNTS_LINE_RE.match(line)
            out.append(f"  {m.group(1)}: {counts_value(m.group(1))}" if m else line)
        return out

    segments = {
        "error_codes": seg_error_codes,
        "counts": rw_counts(span_lines("counts")),
        "verbs": _rw_simple_items(span_lines("verbs"), verb_items, "verbs"),
        "namespaces": _rw_simple_items(span_lines("namespaces"), derived["namespaces"], "namespaces"),
        "builtins": _rw_simple_items(span_lines("builtins"), derived["builtins"], "builtins"),
        "templates": _rw_simple_items(span_lines("templates"), derived["templates"], "templates"),
        "mcp": _rw_mcp(span_lines("mcp"), derived["protocol_versions"]),
        "outcome_transitions": _rw_outcome(span_lines("outcome_transitions"), derived["classes"]),
    }

    out_lines = list(lines[: keys[0][0]])
    for key in names:
        out_lines.extend(segments.get(key) or span_lines(key))
    body = "\n".join(out_lines)
    # dogfood: the emitted body must satisfy the very profile the registries obey
    load_profile_text(body, CANON_PATH + " (emitted)")
    return body.encode("utf-8")


def emit_canon_bytes(root):
    """Header + body · the complete generated canon.yaml (deterministic)."""
    body = emit_canon_body(root)
    return render_canon_header(body) + body


def build(root):
    """Load, validate, and assemble the deterministic outputs (pure, no writes)."""
    law_schema = load_schema(root, "law.schema.json")
    registries_schema = load_schema(root, "registries.schema.json")
    law_validator = jsonschema.Draft202012Validator(law_schema)
    registries_validator = jsonschema.Draft202012Validator(registries_schema)

    errors = []

    law_files = collect_law_files(root)
    if not law_files:
        raise RefusedError(f"no law files under {LAWS_DIR}")
    laws = []
    seen_ids = {}
    for path in law_files:
        relpath = path.relative_to(root).as_posix()
        doc = load_profile_yaml(path, root)
        for idx, entry in enumerate(extract_laws(doc, relpath)):
            label = f"{relpath} · entry[{idx}] ({entry.get('id', '<no-id>')})"
            validate_or_collect(law_validator, entry, label, errors)
            law_id = entry.get("id")
            if law_id in seen_ids:
                errors.append(f"{label} · duplicate law id (first in {seen_ids[law_id]})")
            elif law_id:
                seen_ids[law_id] = relpath
            laws.append(entry)

    registry_docs = collect_registry_docs(root)
    for component, filedocs in registry_docs.items():
        for path, doc in filedocs:
            relpath = path.relative_to(root).as_posix()
            validate_or_collect(registries_validator, doc, f"{relpath} ({component})", errors)

    if not errors:
        resolve_refs(laws, registry_row_ids(registry_docs), errors)

    if errors:
        raise RefusedError("\n".join(errors))

    generator = {
        "identity": GENERATOR_IDENTITY,
        "version": GENERATOR_VERSION,
        "source_sha256": sha256_bytes(Path(__file__).read_bytes()),
    }

    projection = {
        "laws_index_format": 1,
        "generator": generator,
        "pilot": "r11-yaml-profile",
        "law_count": len(laws),
        "source_files": [p.relative_to(root).as_posix() for p in law_files],
        "laws": sorted(laws, key=lambda entry: entry["id"]),
    }
    projection_bytes = canonical_bytes(projection)

    leaves = {}
    for path in law_files:
        leaves[path.relative_to(root).as_posix()] = sha256_bytes(path.read_bytes())
    for component, filedocs in registry_docs.items():
        for path, _doc in filedocs:
            leaves[path.relative_to(root).as_posix()] = sha256_bytes(path.read_bytes())
    leaves[PROJECTION_PATH] = sha256_bytes(projection_bytes)

    row_counts = {c: len(ids) for c, ids in registry_row_ids(registry_docs).items()}
    lock = {
        "ssot_lock_format": 1,
        "generator": generator,
        "components": {
            "laws": [p.relative_to(root).as_posix() for p in law_files],
            **{c: [p.relative_to(root).as_posix() for p, _d in fd]
               for c, fd in registry_docs.items()},
        },
        "leaves": leaves,
        "law_count": len(laws),
        "registry_row_counts": row_counts,
    }
    lock_bytes = canonical_bytes(lock)
    sidecar_bytes = (sha256_bytes(lock_bytes).split(":", 1)[1] + "  ssot.lock\n").encode("utf-8")

    return projection_bytes, lock_bytes, sidecar_bytes


def main(argv):
    args = list(argv[1:])
    check = "--check" in args
    if check:
        args.remove("--check")
    check_canon_mode = "--check-canon" in args
    if check_canon_mode:
        args.remove("--check-canon")
    emit_canon_mode = "--emit-canon" in args
    if emit_canon_mode:
        args.remove("--emit-canon")
    root = Path(args[args.index("--root") + 1]) if "--root" in args else Path(__file__).resolve().parent.parent
    if "--root" in args:
        idx = args.index("--root")
        del args[idx:idx + 2]
    if args or (check + check_canon_mode + emit_canon_mode) > 1:
        print(f"ssot-compiler: unknown arguments: "
              f"{args or '--check · --check-canon · --emit-canon are exclusive modes'}",
              file=sys.stderr)
        print(__doc__, file=sys.stderr)
        return 4
    if not root.is_dir():
        print(f"ssot-compiler: root not found: {root}", file=sys.stderr)
        return 4

    if emit_canon_mode:
        try:
            data = emit_canon_bytes(root)
        except ProfileViolation as exc:
            print(f"REFUSED (profile · R11 gate · exit 3):\n{exc}", file=sys.stderr)
            return 3
        except RefusedError as exc:
            print(f"REFUSED (schema/reference · exit 2):\n{exc}", file=sys.stderr)
            return 2
        (root / CANON_PATH).write_bytes(data)
        print(f"emit-canon OK · {CANON_PATH} {sha256_bytes(data)}")
        print("the flip (SSOT-1 §21-23) · gated surfaces derived from the registries · "
              "16 ledger sections + prose verbatim · GENERATED header + body-sha256 on top")
        return 0

    if check_canon_mode:
        try:
            lines, divergences = check_canon(root)
        except ProfileViolation as exc:
            print(f"REFUSED (profile · R11 gate · exit 3):\n{exc}", file=sys.stderr)
            return 3
        except RefusedError as exc:
            print(f"REFUSED (schema/reference · exit 2):\n{exc}", file=sys.stderr)
            return 2
        for line in lines:
            print(line)
        if divergences:
            print("CANON DIVERGENCE (exit 5):\n" + "\n".join(divergences), file=sys.stderr)
            return 5
        gated = sum(1 for l in lines if l.startswith(("PARITY", "COUNTS")))
        skipped = sum(1 for l in lines if l.startswith("SKIP"))
        flip = " · generated projection byte-verified (the flip)" \
            if any(l.startswith("GENERATED") for l in lines) else ""
        print(f"check-canon OK · one truth · {gated} gated surfaces · "
              f"{skipped} declared skips (ledger){flip}")
        return 0

    try:
        projection_bytes, lock_bytes, sidecar_bytes = build(root)
    except ProfileViolation as exc:
        print(f"REFUSED (profile · R11 gate · exit 3):\n{exc}", file=sys.stderr)
        return 3
    except RefusedError as exc:
        print(f"REFUSED (schema/reference · exit 2):\n{exc}", file=sys.stderr)
        return 2

    outputs = [
        (root / PROJECTION_PATH, projection_bytes),
        (root / LOCK_PATH, lock_bytes),
        (root / LOCK_SIDECAR_PATH, sidecar_bytes),
    ]

    if check:
        drift = []
        for path, expected in outputs:
            rel = path.relative_to(root).as_posix()
            if not path.is_file():
                drift.append(f"{rel}: missing on disk")
            elif path.read_bytes() != expected:
                drift.append(f"{rel}: bytes differ from regeneration")
        if drift:
            print("DRIFT (exit 1):\n" + "\n".join(drift), file=sys.stderr)
            return 1
        print(f"check OK · byte-identical ×{len(outputs)} outputs")
    else:
        for path, data in outputs:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        print(f"write OK · {len(outputs)} outputs")

    print(f"projection {PROJECTION_PATH} {sha256_bytes(projection_bytes)}")
    print(f"lock {LOCK_PATH} {sha256_bytes(lock_bytes)} (detached in {LOCK_SIDECAR_PATH})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
