#!/usr/bin/env python3
"""ssot-compiler v0 · C0 SANDBOX (estate · zero repo mutation)

Contract source: design-pack-pre1/01_STRUCTURED_LAW_SCHEMA.md §6 + PRE1_C0_SCOPE.md §3
+ PRE1_C0_FIRST_72H_PLAN.md T+24h. Sandbox instance: parses canon/laws/*.yaml, validates
every law entry against schemas/law.schema.json (SEALED, consumed as-is), validates the
12 registry documents against schemas/registries.schema.json, resolves law refs into the
seeded registries, emits ONE deterministic projection (projections/laws-index.json,
stable sort by law id, canonical JSON, NFC, LF) plus canon/ssot.lock (leaf digests only,
digest-dag layer 1, own digest DETACHED in canon/ssot.lock.sha256 per PAA-006).

Modes
  write (default)   regenerate projection + lock + sidecar, print digests
  --check           regenerate in memory, byte-compare against disk, never write
  --check-canon     v0.2 (canon-flip · MIG-canon-yaml) · parity gate registries <-> canon.yaml
                    ("jamais deux vérités" · SSOT-1). For every IMPORTED section the gate
                    verifies count == len(items) AND the item set == the registry row set
                    (scoped per section: surface kind=verb/namespace spellings · builtins
                    "nika:"+name ids · templates ids · error_codes as a subset of the
                    diagnostics ids with registry-ahead rows reported · mcp.protocol_versions
                    via the bijective id transform · outcome_transitions.classes vs the
                    sealed outcome_class enum · the derivable half of error_namespaces).
                    Sections WITHOUT a sealed registry home are DECLARED skips mirroring
                    canon/EXCEPTIONS.md (the §18 exception ledger) — the two lists must
                    stay in lockstep. Read-only · zero network · deterministic output.

Exit codes
  0  OK (write done, --check byte-identical, or --check-canon full parity)
  1  --check drift (any regenerated byte differs from disk)
  2  schema/reference refusal (law or registry row invalid, unresolved ref, dup law id)
  3  input profile violation (R11 gate: anchor, alias, merge key, duplicate key,
     custom tag, non-string key, NaN/Infinity in a canon source file)
  4  usage or environment error
  5  --check-canon divergence (every diverging section + exact item names listed)

Determinism: sorted file iteration, sorted JSON keys, NFC, LF, no timestamps, no
absolute paths in outputs. Zero network: jsonschema validates with local schemas only.

Dependencies: python3 stdlib + jsonschema + PyYAML. FINDING-09: the sandbox rule said
stdlib+jsonschema only, but the mandated inputs are YAML; PyYAML (already the spec
reference-model parser, see spec repo reference/semantics.py) is used for INPUT parsing
only, wrapped in the R11-enforcing loader below (the dogfood gate: our own SSOT sources
must satisfy the very profile the pilot laws import).
"""

import hashlib
import json
import sys
import unicodedata
from pathlib import Path

try:
    import yaml
    import jsonschema
except ImportError as exc:  # pragma: no cover
    print(f"ssot-compiler: missing dependency: {exc}", file=sys.stderr)
    sys.exit(4)

GENERATOR_IDENTITY = "ssot-compiler"
GENERATOR_VERSION = "0.2.0-sandbox"

# The 13 SSOT components (machine/registries-inventory.json, consumed as-is).
REGISTRY_COMPONENTS = {
    "surface": "canon/surface.yaml",
    "grammar": "canon/grammar.yaml",
    "types": "canon/types.yaml",
    "diagnostics": "canon/diagnostics",  # registry-modular (dir)
    "builtins": "canon/builtins.yaml",
    "features": "canon/features.yaml",
    "templates": "canon/templates/registry.yaml",
    "snippets": "canon/snippets/registry.yaml",
    "conformance": "canon/conformance.yaml",
    "tombstones": "canon/tombstones.yaml",
    "projections": "canon/projections.yaml",
    "migrations": "canon/migrations.yaml",
}
LAWS_DIR = "canon/laws"
PROJECTION_PATH = "projections/laws-index.json"
LOCK_PATH = "canon/ssot.lock"
LOCK_SIDECAR_PATH = "canon/ssot.lock.sha256"

YAML_CORE_TAGS = {
    "tag:yaml.org,2002:str", "tag:yaml.org,2002:int", "tag:yaml.org,2002:float",
    "tag:yaml.org,2002:bool", "tag:yaml.org,2002:null", "tag:yaml.org,2002:map",
    "tag:yaml.org,2002:seq",
}


class ProfileViolation(Exception):
    """R11 gate: the canon source violates the Nika YAML profile."""


class RefusedError(Exception):
    """Schema or reference refusal (exit 2)."""


def _mark(mark):
    return f"line {mark.line + 1}, column {mark.column + 1}" if mark else "unknown position"


def profile_scan_events(text, relpath):
    """R11 event-level gate: anchors, aliases, merge keys, custom tags (points 1, 3, 13)."""
    for event in yaml.parse(text):
        if isinstance(event, yaml.events.AliasEvent):
            raise ProfileViolation(
                f"{relpath}: YAML alias (*{event.anchor}) at {_mark(event.start_mark)} · "
                "R11 point 1: the Nika profile forbids aliases")
        anchor = getattr(event, "anchor", None)
        if anchor is not None:
            raise ProfileViolation(
                f"{relpath}: YAML anchor (&{anchor}) at {_mark(event.start_mark)} · "
                "R11 points 1+3: forbidden even when never referenced")
        if isinstance(event, yaml.events.ScalarEvent):
            if event.style is None and event.value == "<<":
                raise ProfileViolation(
                    f"{relpath}: YAML merge key (<<) at {_mark(event.start_mark)} · "
                    "R11 point 1: the Nika profile forbids merge keys")
            if event.tag is not None and event.tag not in YAML_CORE_TAGS:
                raise ProfileViolation(
                    f"{relpath}: custom tag {event.tag} at {_mark(event.start_mark)} · "
                    "R11 point 13: only the YAML core schema is admitted")


class ProfileLoader(yaml.SafeLoader):
    """R11 construction-level gate: duplicate keys, non-string keys, NaN/Infinity."""

    def construct_mapping(self, node, deep=False):
        seen = set()
        for key_node, _value in node.value:
            key = self.construct_object(key_node, deep=True)
            if not isinstance(key, str):
                raise ProfileViolation(
                    f"non-string mapping key {key!r} at {_mark(key_node.start_mark)} · "
                    "R11 point 13: mapping keys are strings")
            if key in seen:
                raise ProfileViolation(
                    f"duplicate mapping key {key!r} at {_mark(key_node.start_mark)} · "
                    "R11 points 5+13: duplicate keys are refused")
            seen.add(key)
        return super().construct_mapping(node, deep=deep)


def _construct_profile_float(loader, node):
    value = yaml.SafeLoader.construct_yaml_float(loader, node)
    if value != value or value in (float("inf"), float("-inf")):
        raise ProfileViolation(
            f"non-finite float {node.value!r} at {_mark(node.start_mark)} · "
            "R11 point 13: NaN/Infinity are refused")
    return value


ProfileLoader.add_constructor("tag:yaml.org,2002:float", _construct_profile_float)


def load_profile_yaml(path, root):
    relpath = path.relative_to(root).as_posix()
    text = path.read_text(encoding="utf-8")
    if text.startswith("\ufeff"):
        raise ProfileViolation(f"{relpath}: BOM present · R11 point 13 (unicode contract)")
    profile_scan_events(text, relpath)
    try:
        doc = yaml.load(text, Loader=ProfileLoader)
    except ProfileViolation as exc:
        raise ProfileViolation(f"{relpath}: {exc}") from None
    except yaml.YAMLError as exc:
        raise RefusedError(f"{relpath}: YAML parse error: {exc}") from None
    return doc


def canonical_bytes(obj):
    """Canonical JSON: sorted keys, minimal separators, NFC, LF, trailing newline."""
    text = json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return (unicodedata.normalize("NFC", text) + "\n").encode("utf-8")


def sha256_bytes(data):
    return "sha256:" + hashlib.sha256(data).hexdigest()


def load_schema(root, name):
    path = root / "schemas" / name
    if not path.is_file():
        raise RefusedError(f"missing sealed schema: schemas/{name}")
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def validate_or_collect(validator, instance, label, errors):
    for err in sorted(validator.iter_errors(instance), key=lambda e: list(e.absolute_path)):
        pointer = "/" + "/".join(str(p) for p in err.absolute_path)
        errors.append(f"{label} · at {pointer or '/'} · {err.message}")


def collect_law_files(root):
    laws_dir = root / LAWS_DIR
    if not laws_dir.is_dir():
        raise RefusedError(f"missing laws component dir: {LAWS_DIR}")
    return sorted(p for p in laws_dir.glob("*.yaml") if p.is_file())


def extract_laws(doc, relpath):
    """Accept the two documented shapes: bare list, or mapping with a `laws` list."""
    if isinstance(doc, list):
        return doc
    if isinstance(doc, dict) and isinstance(doc.get("laws"), list):
        return doc["laws"]
    raise RefusedError(
        f"{relpath}: unsupported laws document shape (expected a list of entries "
        "or a mapping with a `laws` list)")


def collect_registry_docs(root):
    docs = {}
    for component, rel in REGISTRY_COMPONENTS.items():
        path = root / rel
        if component == "diagnostics":
            if not path.is_dir():
                raise RefusedError(f"missing registry-modular dir: {rel}")
            files = sorted(p for p in path.glob("*.yaml") if p.is_file())
            if not files:
                raise RefusedError(f"empty registry-modular dir: {rel}")
            docs[component] = [(p, load_profile_yaml(p, root)) for p in files]
        else:
            if not path.is_file():
                raise RefusedError(f"missing registry file: {rel}")
            docs[component] = [(path, load_profile_yaml(path, root))]
    return docs


def registry_row_ids(docs):
    ids = {}
    for component, filedocs in docs.items():
        rows = []
        for _path, doc in filedocs:
            rows.extend(doc.get(component) or [])
        ids[component] = {row.get("id") for row in rows if isinstance(row, dict)}
    return ids


def iter_typed_refs(law):
    for ref in law.get("inputs", []):
        yield "inputs", ref
    for ref in law.get("judgment", {}).get("generated_facts", []):
        yield "judgment.generated_facts", ref
    subject = law.get("domain_payload", {}).get("subject")
    if isinstance(subject, dict):
        yield "domain_payload.subject", subject


def resolve_refs(laws, row_ids, errors):
    """ir refs are runtime/IR symbols (unresolvable in canon by design, like the sealed
    examples' required_capabilities). Every other registry ref must hit a seeded row."""
    for law in laws:
        law_id = law.get("id", "<no-id>")
        for where, ref in iter_typed_refs(law):
            registry = ref.get("registry")
            rid = ref.get("id")
            if registry in (None, "ir", "laws"):
                continue
            if registry not in row_ids:
                errors.append(f"{law_id} · {where} · unknown registry {registry!r}")
                continue
            if rid not in row_ids[registry]:
                errors.append(
                    f"{law_id} · {where} · unresolved ref {registry}:{rid} "
                    "(no seeded row · SSOT-1 §12 orphan)")


# ---------------------------------------------------------------- check-canon (v0.2)

CANON_PATH = "canon.yaml"

# Declared skips · MUST mirror canon/EXCEPTIONS.md (SSOT-1 §18 exception ledger).
# A canon.yaml section neither imported below nor listed here = drift (rc 5).
CANON_EXCEPTIONS = {
    "counts": "derived by this gate (count == len(items) verified per section) · never copied",
    "providers": "needs registry home ruling (C1) · see canon/EXCEPTIONS.md",
    "extract_modes": "needs registry home ruling (C1) · see canon/EXCEPTIONS.md",
    "error_categories": "no category field in the sealed diagnosticRow · carried in row notes · ruling owed C1 (CF-10)",
    "outcome_transitions.legal": "table-13 registry home owed C1 · kernel-ahead causes = FINDINGS CF-07/CF-08",
    "outcome_transitions.payload": "table-13 registry home owed C1 (rides the same ruling as .legal)",
    "pillars": "studio vocabulary · stays authored per operator reco",
    "lifecycle_product": "studio vocabulary · stays authored per operator reco",
    "lifecycle_decision": "studio vocabulary · stays authored per operator reco",
    "lifecycle_risk": "studio vocabulary · stays authored per operator reco",
    "diamond_layers": "studio vocabulary · stays authored per operator reco",
    "steal_pattern_tiers": "studio vocabulary · stays authored per operator reco",
    "severity": "studio vocabulary · stays authored per operator reco",
    "mcp.tools": "engine-verified projection (crates/nika-mcp/src/tools.rs) · features home ruling owed C1",
    "canonical_phrasing": "one-voice phrasing registry · canon/snippets home ruling owed C1",
    "schema_version": "canon.yaml projection marker · dies at the flip (GENERATED header · SSOT-1 §23)",
}

# canon.yaml namespaces declared code-free at v0.1 (canon.yaml + spec/05-errors.md
# concrete table both carry zero codes for them · FINDING CF-09 · ledger row).
CANON_DECLARED_EMPTY_NAMESPACES = {"NIKA-IMPL", "NIKA-PROVIDER"}


def _canon_item_names(section):
    """Item spellings for a canon.yaml section (dict items carry name/code keys)."""
    items = section["items"]
    if isinstance(items, dict):  # providers-style nested groups
        return [x for group in items.values() for x in group]
    out = []
    for it in items:
        if isinstance(it, dict):
            out.append(it.get("name") or it.get("code"))
        else:
            out.append(it)
    return out


def _fmt_set(values, cap=12):
    values = sorted(values)
    shown = " ".join(values[:cap])
    return shown + (f" (+{len(values) - cap} more)" if len(values) > cap else "")


def check_canon(root):
    """Parity gate registries <-> canon.yaml (read-only). Returns (lines, divergences)."""
    canon_file = root / CANON_PATH
    if not canon_file.is_file():
        raise RefusedError(f"missing canon source: {CANON_PATH}")
    canon = load_profile_yaml(canon_file, root)
    registries_schema = load_schema(root, "registries.schema.json")
    docs = collect_registry_docs(root)

    def rows(component):
        out = []
        for _path, doc in docs[component]:
            out.extend(doc.get(component) or [])
        return out

    lines, divergences = [], []

    def gate(section, canon_names, row_names, subset_only=False, extra_note=None):
        canon_set, row_set = set(canon_names), set(row_names)
        declared = canon.get(section) if "." not in section else None
        count = declared.get("count") if isinstance(declared, dict) else None
        if count is not None and count != len(canon_names):
            divergences.append(
                f"{section}: canon count {count} != len(items) {len(canon_names)} (intra-canon self-check)")
        missing = canon_set - row_set
        if missing:
            divergences.append(f"{section}: canon items with NO registry row: {_fmt_set(missing)}")
        if not subset_only:
            extra = row_set - canon_set
            if extra:
                divergences.append(f"{section}: registry rows with NO canon item: {_fmt_set(extra)}")
        if not missing and (subset_only or row_set == canon_set):
            lines.append(f"PARITY {section} · canon {len(canon_set)} == rows {len(row_set & canon_set)}"
                         + (f" · {extra_note}" if extra_note else ""))

    # counts block · every counts.<key> must equal its section's count/len (derived, never copied)
    counts = canon.get("counts", {})
    for key, value in sorted(counts.items()):
        if key == "mcp_tools":
            section, names = "mcp.tools", _canon_item_names(canon["mcp"]["tools"])
        elif key == "mcp_protocol_versions":
            section, names = "mcp.protocol_versions", _canon_item_names(canon["mcp"]["protocol_versions"])
        else:
            section, names = key, _canon_item_names(canon[key])
        if value != len(names):
            divergences.append(f"counts.{key}: {value} != len({section}.items) {len(names)}")
    lines.append(f"COUNTS · {len(counts)} keys verified against len(items) (derived · never copied)")

    # verbs + namespaces -> canon/surface.yaml (scoped by row kind · spelling carries the word)
    surface_rows = rows("surface")
    gate("verbs", _canon_item_names(canon["verbs"]),
         [r["spelling"] for r in surface_rows if r.get("kind") == "verb"])
    gate("namespaces", _canon_item_names(canon["namespaces"]),
         [r["spelling"] for r in surface_rows if r.get("kind") == "namespace"])

    # builtins -> canon/builtins.yaml (row id = "nika:" + item · duplicate row ids = a second truth)
    builtin_ids = [r["id"] for r in rows("builtins")]
    dupes = {i for i in builtin_ids if builtin_ids.count(i) > 1}
    if dupes:
        divergences.append(f"builtins: duplicate registry rows for {_fmt_set(dupes)} (a second truth)")
    gate("builtins", [f"nika:{n}" for n in _canon_item_names(canon["builtins"])], builtin_ids)

    # templates -> canon/templates/registry.yaml (row id = item)
    gate("templates", _canon_item_names(canon["templates"]), [r["id"] for r in rows("templates")])

    # error_codes -> canon/diagnostics (subset · kernel-born rows may run AHEAD of the canon projection)
    diag_rows = rows("diagnostics")
    diag_ids = {r["id"] for r in diag_rows}
    canon_code_names = _canon_item_names(canon["error_codes"])
    ahead = diag_ids - set(canon_code_names)
    gate("error_codes", canon_code_names, diag_ids, subset_only=True,
         extra_note=(f"registry-ahead rows (not yet in canon.yaml · CF-05): {_fmt_set(ahead)}" if ahead else None))

    # error_namespaces · derivable half GATED: every canon-code row's namespace must be a canon namespace
    canon_ns = set(_canon_item_names(canon["error_namespaces"]))
    derived_ns = {"NIKA-" + r["namespace"] for r in diag_rows if r["id"] in set(canon_code_names)}
    outside = derived_ns - canon_ns
    if outside:
        divergences.append(f"error_namespaces: row namespaces outside the canon set: {_fmt_set(outside)}")
    uncovered = canon_ns - derived_ns
    undeclared_empty = uncovered - CANON_DECLARED_EMPTY_NAMESPACES
    if undeclared_empty:
        divergences.append(
            f"error_namespaces: canon namespaces with zero rows and NOT declared empty (CF-09 ledger): "
            f"{_fmt_set(undeclared_empty)}")
    if not outside and not undeclared_empty:
        lines.append(f"PARITY error_namespaces · derived {len(derived_ns)}/{len(canon_ns)} · declared-empty "
                     f"(ledger CF-09): {_fmt_set(uncovered & CANON_DECLARED_EMPTY_NAMESPACES)}")

    # mcp.protocol_versions -> canon/features.yaml (bijective id transform · dashes -> underscores)
    expected_feats = {"mcp.protocol." + v.replace("-", "_")
                      for v in _canon_item_names(canon["mcp"]["protocol_versions"])}
    actual_feats = {r["id"] for r in rows("features") if r["id"].startswith("mcp.protocol.")}
    gate("mcp.protocol_versions", expected_feats, actual_feats)

    # outcome_transitions.classes vs the SEALED outcome_class enum (one class table · terminal never a class)
    classes = canon["outcome_transitions"]["classes"]
    enum_classes = registries_schema["$defs"]["diagnosticRow"]["properties"]["outcome_class"]["enum"]
    if set(classes) != set(enum_classes):
        divergences.append(
            f"outcome_transitions.classes: canon {sorted(classes)} != sealed outcome_class enum {sorted(enum_classes)}")
    else:
        lines.append(f"PARITY outcome_transitions.classes · canon == sealed enum ({len(classes)} classes)")
    for table in ("legal", "payload"):
        keys = set(canon["outcome_transitions"][table])
        if keys != set(classes):
            divergences.append(f"outcome_transitions.{table}: keys {sorted(keys)} != classes {sorted(classes)}")

    for section in sorted(CANON_EXCEPTIONS):
        lines.append(f"SKIP {section} · exception ledger (canon/EXCEPTIONS.md) · {CANON_EXCEPTIONS[section]}")

    return lines, divergences


def build(root):
    """Load, validate, and assemble the deterministic outputs (pure, no writes)."""
    law_schema = load_schema(root, "law.schema.json")
    registries_schema = load_schema(root, "registries.schema.json")
    law_validator = jsonschema.Draft202012Validator(law_schema)
    registries_validator = jsonschema.Draft202012Validator(registries_schema)

    errors = []

    law_files = collect_law_files(root)
    if not law_files:
        raise RefusedError(f"no law files under {LAWS_DIR}")
    laws = []
    seen_ids = {}
    for path in law_files:
        relpath = path.relative_to(root).as_posix()
        doc = load_profile_yaml(path, root)
        for idx, entry in enumerate(extract_laws(doc, relpath)):
            label = f"{relpath} · entry[{idx}] ({entry.get('id', '<no-id>')})"
            validate_or_collect(law_validator, entry, label, errors)
            law_id = entry.get("id")
            if law_id in seen_ids:
                errors.append(f"{label} · duplicate law id (first in {seen_ids[law_id]})")
            elif law_id:
                seen_ids[law_id] = relpath
            laws.append(entry)

    registry_docs = collect_registry_docs(root)
    for component, filedocs in registry_docs.items():
        for path, doc in filedocs:
            relpath = path.relative_to(root).as_posix()
            validate_or_collect(registries_validator, doc, f"{relpath} ({component})", errors)

    if not errors:
        resolve_refs(laws, registry_row_ids(registry_docs), errors)

    if errors:
        raise RefusedError("\n".join(errors))

    generator = {
        "identity": GENERATOR_IDENTITY,
        "version": GENERATOR_VERSION,
        "source_sha256": sha256_bytes(Path(__file__).read_bytes()),
    }

    projection = {
        "laws_index_format": 1,
        "generator": generator,
        "pilot": "r11-yaml-profile",
        "law_count": len(laws),
        "source_files": [p.relative_to(root).as_posix() for p in law_files],
        "laws": sorted(laws, key=lambda entry: entry["id"]),
    }
    projection_bytes = canonical_bytes(projection)

    leaves = {}
    for path in law_files:
        leaves[path.relative_to(root).as_posix()] = sha256_bytes(path.read_bytes())
    for component, filedocs in registry_docs.items():
        for path, _doc in filedocs:
            leaves[path.relative_to(root).as_posix()] = sha256_bytes(path.read_bytes())
    leaves[PROJECTION_PATH] = sha256_bytes(projection_bytes)

    row_counts = {c: len(ids) for c, ids in registry_row_ids(registry_docs).items()}
    lock = {
        "ssot_lock_format": 1,
        "generator": generator,
        "components": {
            "laws": [p.relative_to(root).as_posix() for p in law_files],
            **{c: [p.relative_to(root).as_posix() for p, _d in fd]
               for c, fd in registry_docs.items()},
        },
        "leaves": leaves,
        "law_count": len(laws),
        "registry_row_counts": row_counts,
    }
    lock_bytes = canonical_bytes(lock)
    sidecar_bytes = (sha256_bytes(lock_bytes).split(":", 1)[1] + "  ssot.lock\n").encode("utf-8")

    return projection_bytes, lock_bytes, sidecar_bytes


def main(argv):
    args = list(argv[1:])
    check = "--check" in args
    if check:
        args.remove("--check")
    check_canon_mode = "--check-canon" in args
    if check_canon_mode:
        args.remove("--check-canon")
    root = Path(args[args.index("--root") + 1]) if "--root" in args else Path(__file__).resolve().parent.parent
    if "--root" in args:
        idx = args.index("--root")
        del args[idx:idx + 2]
    if args or (check and check_canon_mode):
        print(f"ssot-compiler: unknown arguments: {args or '--check + --check-canon are exclusive modes'}",
              file=sys.stderr)
        print(__doc__, file=sys.stderr)
        return 4
    if not root.is_dir():
        print(f"ssot-compiler: root not found: {root}", file=sys.stderr)
        return 4

    if check_canon_mode:
        try:
            lines, divergences = check_canon(root)
        except ProfileViolation as exc:
            print(f"REFUSED (profile · R11 gate · exit 3):\n{exc}", file=sys.stderr)
            return 3
        except RefusedError as exc:
            print(f"REFUSED (schema/reference · exit 2):\n{exc}", file=sys.stderr)
            return 2
        for line in lines:
            print(line)
        if divergences:
            print("CANON DIVERGENCE (exit 5):\n" + "\n".join(divergences), file=sys.stderr)
            return 5
        gated = sum(1 for l in lines if l.startswith(("PARITY", "COUNTS")))
        skipped = sum(1 for l in lines if l.startswith("SKIP"))
        print(f"check-canon OK · one truth · {gated} gated surfaces · {skipped} declared skips (ledger)")
        return 0

    try:
        projection_bytes, lock_bytes, sidecar_bytes = build(root)
    except ProfileViolation as exc:
        print(f"REFUSED (profile · R11 gate · exit 3):\n{exc}", file=sys.stderr)
        return 3
    except RefusedError as exc:
        print(f"REFUSED (schema/reference · exit 2):\n{exc}", file=sys.stderr)
        return 2

    outputs = [
        (root / PROJECTION_PATH, projection_bytes),
        (root / LOCK_PATH, lock_bytes),
        (root / LOCK_SIDECAR_PATH, sidecar_bytes),
    ]

    if check:
        drift = []
        for path, expected in outputs:
            rel = path.relative_to(root).as_posix()
            if not path.is_file():
                drift.append(f"{rel}: missing on disk")
            elif path.read_bytes() != expected:
                drift.append(f"{rel}: bytes differ from regeneration")
        if drift:
            print("DRIFT (exit 1):\n" + "\n".join(drift), file=sys.stderr)
            return 1
        print(f"check OK · byte-identical ×{len(outputs)} outputs")
    else:
        for path, data in outputs:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        print(f"write OK · {len(outputs)} outputs")

    print(f"projection {PROJECTION_PATH} {sha256_bytes(projection_bytes)}")
    print(f"lock {LOCK_PATH} {sha256_bytes(lock_bytes)} (detached in {LOCK_SIDECAR_PATH})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
