#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>
#
# starters-projector.py — project stdlib/verb-starters-v0.1.yaml (the
# per-verb task-body starters SSOT) to every consumer surface. Values
# change in the YAML FIRST, then re-project. Companion of
# design-projector.py (same sibling law, same exit codes).
#
#   TARGET 0 · in-repo      shape self-check (verbs == the canonical 4 ·
#                           kebab ids unique · label/hint budgets · body
#                           opens on `<verb>:`) PLUS the oracle proof —
#                           every body, scaffolded into a minimal
#                           workflow, must validate against the
#                           conformance runner. Unproven starters never
#                           project.
#   TARGET 1 · nika-vscode  src/core/verbStarters.generated.ts
#
# Sibling resolution (env-overridable · missing sibling = skipped so a
# standalone spec clone projects nothing):
#   vscode · $NIKA_VSCODE_SRC · else <spec-root>/../vscode/repo/src ·
#            else <spec-root>/../../vscode/repo/src · else .../vscode/src
#
# Exit codes · 0 in-sync/written · 1 drift (--check) · 2 environment or
# schema error.

import json
import os
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("starters-projector · pyyaml required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

SPEC_ROOT = Path(__file__).resolve().parent.parent
STARTERS_PATH = SPEC_ROOT / "stdlib" / "verb-starters-v0.1.yaml"

CANON_VERBS = ("infer", "exec", "invoke", "agent")
KEBAB_RE = re.compile(r"^[a-z][a-z0-9-]*$")
INPUT_RE = re.compile(r"\$\{\{\s*inputs\.([a-z][a-z0-9_]*)")


def fail(msg: str, code: int = 2) -> None:
    print(f"starters-projector · {msg}", file=sys.stderr)
    sys.exit(code)


def load_starters() -> dict:
    if not STARTERS_PATH.exists():
        fail("stdlib/verb-starters-v0.1.yaml missing")
    data = yaml.safe_load(STARTERS_PATH.read_text())
    if data.get("starters_version") != 1:
        fail("unknown starters_version (want 1)")
    verbs = data.get("verbs", {})
    if tuple(verbs.keys()) != CANON_VERBS:
        fail(f"verbs must be exactly {CANON_VERBS} in order, got {tuple(verbs.keys())}")
    seen: set[str] = set()
    for verb, starters in verbs.items():
        if not starters:
            fail(f"verb {verb} has no starters")
        for s in starters:
            sid = s.get("id", "")
            if not KEBAB_RE.match(sid):
                fail(f"starter id {sid!r} is not kebab-case")
            if sid in seen:
                fail(f"starter id {sid!r} duplicated")
            seen.add(sid)
            if not s.get("label") or len(s["label"]) > 40:
                fail(f"{sid}: label missing or over the 40-char picker budget")
            if not s.get("hint") or len(s["hint"]) > 120:
                fail(f"{sid}: hint missing or over the 120-char detail budget")
            body = s.get("body", "")
            if not body.startswith(f"{verb}:"):
                fail(f"{sid}: body must open on `{verb}:`, got {body.splitlines()[:1]}")
    return data


def scaffold(starter_id: str, body: str) -> str:
    """Wrap a verb block in the minimal valid workflow the oracle can judge."""
    inputs_found = sorted(set(INPUT_RE.findall(body)))
    out = [
        "nika: v1",
        "workflow:",
        f"  id: {starter_id}",
        '  description: "starter proof — generated by starters-projector"',
        "model: mock/echo",
    ]
    if inputs_found:
        # R3a · a starter parameter is a typed workflow `inputs:` declaration
        # (the caller supplies it) · the probe declares each as a string input
        out.append("inputs:")
        out.extend(f"  {v}: {{ type: string }}" for v in inputs_found)
    out.append("tasks:")
    out.append("  probe:")
    out.extend(("    " + line) if line.strip() else line
               for line in body.rstrip("\n").split("\n"))
    return "\n".join(out) + "\n"


def prove(data: dict) -> None:
    """TARGET 0 oracle proof — every starter validates, or nothing projects."""
    sys.path.insert(0, str(SPEC_ROOT / "conformance"))
    try:
        from runner import load_canon, load_schema, validate_text  # noqa: PLC0415
    except ImportError as e:
        fail(f"conformance runner unavailable ({e}) — run from a full spec checkout")
    validator = load_schema()
    canon = load_canon()
    bad = 0
    for verb in CANON_VERBS:
        for s in data["verbs"][verb]:
            verdict = validate_text(scaffold(s["id"], s["body"]), validator, canon)
            if not verdict["valid"]:
                bad += 1
                for err in verdict["errors"]:
                    print(f"starters-projector · {s['id']} FAILS the oracle · "
                          f"{err.get('code', err.get('namespace'))} · {err['detail']}",
                          file=sys.stderr)
    if bad:
        fail(f"{bad} starter(s) fail the conformance oracle — fix the SSOT, never the consumer")


def emit_ts(data: dict) -> str:
    j = lambda v: json.dumps(v, ensure_ascii=False)  # noqa: E731
    lines = [
        "// verbStarters.generated.ts — AUTO-GENERATED by nika-spec",
        "// scripts/starters-projector.py from stdlib/verb-starters-v0.1.yaml",
        "// (the per-verb task-body starters SSOT). DO NOT EDIT — values change",
        "// SPEC-FIRST. Regenerate: python3 scripts/starters-projector.py --write",
        "// Drift gate: --check (spec CI + consumer gates).",
        "",
        "export interface VerbStarter {",
        "  readonly id: string;",
        "  /** The picker row (≤ 40 chars). */",
        "  readonly label: string;",
        "  /** The picker detail — teaches the why (≤ 120 chars). */",
        "  readonly hint: string;",
        "  /** The verb block, unindented (first line is `<verb>:`) — consumers re-indent. */",
        "  readonly body: string;",
        "}",
        "",
        "export type NikaVerb = 'infer' | 'exec' | 'invoke' | 'agent';",
        "",
        "export const NIKA_VERB_STARTERS: Record<NikaVerb, readonly VerbStarter[]> = {",
    ]
    for verb in CANON_VERBS:
        lines.append(f"  {verb}: [")
        for s in data["verbs"][verb]:
            lines.append("    {")
            lines.append(f"      id: {j(s['id'])},")
            lines.append(f"      label: {j(s['label'])},")
            lines.append(f"      hint: {j(s['hint'])},")
            lines.append(f"      body: {j(s['body'])},")
            lines.append("    },")
        lines.append("  ],")
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def resolve_vscode_src() -> Path | None:
    env = os.environ.get("NIKA_VSCODE_SRC")
    if env:
        p = Path(env)
        return p if p.is_dir() else None
    for cand in ("../vscode/repo/src", "../../vscode/repo/src", "../vscode/src"):
        p = (SPEC_ROOT / cand).resolve()
        if p.is_dir():
            return p
    return None


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode not in ("--check", "--write"):
        fail("usage: starters-projector.py [--check | --write]")
    data = load_starters()
    prove(data)
    ts = emit_ts(data)

    drift = False
    vscode_src = resolve_vscode_src()
    if vscode_src is None:
        print("starters-projector · vscode sibling absent — TARGET 1 skipped")
    else:
        target = vscode_src / "core" / "verbStarters.generated.ts"
        current = target.read_text() if target.exists() else None
        if mode == "--write":
            if current != ts:
                target.write_text(ts)
                print(f"starters-projector · wrote {target}")
            else:
                print(f"starters-projector · {target} already in sync")
        elif current != ts:
            drift = True
            print(f"starters-projector · DRIFT · {target} "
                  f"({'missing' if current is None else 'differs'}) — re-run with --write",
                  file=sys.stderr)
    if drift:
        return 1
    print(f"starters-projector · TARGET 0 proven · "
          f"{sum(len(v) for v in data['verbs'].values())} starters across {len(CANON_VERBS)} verbs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
