#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Project filled lessons and the authoring index from canonical templates.

Workflow logic is authored once. rehearsals.yaml supplies literal slot answers;
the generated lessons are embedded by the engine and displayed by the docs.
"""
import argparse
from pathlib import Path
import re
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
SLOT = re.compile(r"<SLOT:[^>\n]+>")
SLUG = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")


def render(root: Path) -> dict[Path, str]:
    registry = yaml.safe_load((root / "canon/templates/registry.yaml").read_text())["templates"]
    names = [row["id"] for row in registry]
    if len(names) != len(set(names)):
        raise ValueError("Duplicate template id")
    rows = yaml.safe_load((root / "templates/rehearsals.yaml").read_text())["rehearsals"]
    outputs = {}
    examples = {}
    for row in rows:
        name, example, fill = row["template"], row["example"], row["fill"]
        if name not in names or not SLUG.fullmatch(example) or not re.match(r"^\d{2}-", example):
            raise ValueError(f"Invalid rehearsal source or lesson id: {row}")
        if name in examples or example in examples.values():
            raise ValueError("Duplicate rehearsal source or lesson id")
        if not isinstance(fill, str) or SLOT.search(fill):
            raise ValueError(f"Invalid slot answer for {name}")
        source = (root / "templates" / f"{name}.nika.yaml").read_text()
        # These rehearsals fill scalar VALUE slots. Editing the YAML object
        # avoids corrupting quotes, newlines, CEL expressions or backslashes.
        count = 0

        def fill_value(value):
            nonlocal count
            if isinstance(value, str):
                count += len(SLOT.findall(value))
                return SLOT.sub(lambda _: fill, value)
            if isinstance(value, list):
                return [fill_value(v) for v in value]
            if isinstance(value, dict):
                if any(isinstance(k, str) and SLOT.search(k) for k in value):
                    raise ValueError(f"{name}: expected one scalar value slot, found a key slot")
                return {k: fill_value(v) for k, v in value.items()}
            return value

        body = fill_value(yaml.safe_load(source))
        if count != 1:
            raise ValueError(f"{name}: expected one scalar value slot, found {count}")
        banner = source.split("\nnika:", 1)[0]
        banner = banner.replace(f"# TEMPLATE · {name} ·", f"# {example[:2]} ·")
        banner = banner.replace("fill the SLOT; ", "")
        banner = banner.replace("nika run <file>", f"nika run examples/{example}.nika.yaml")
        banner += f"\n# GENERATED by scripts/template-rehearsals.py from templates/{name}.nika.yaml.\n"
        outputs[root / "examples" / f"{example}.nika.yaml"] = banner + yaml.safe_dump(body, sort_keys=False, allow_unicode=True, width=100)
        golden = root / "templates" / f"{name}.nika.yaml.golden.json"
        outputs[root / "examples" / f"{example}.nika.yaml.golden.json"] = golden.read_text()
        examples[name] = example

    # REUSE-IgnoreStart
    lines = ["<!-- SPDX-License-Identifier: Apache-2.0 -->", "<!-- GENERATED by scripts/template-rehearsals.py; edit templates and rehearsals.yaml. -->",
             "# Native authoring index", "", "Discover the installed set with `nika new '?'` and `nika try --all`.",
             "Copy a skeleton with `nika new <template> my-workflow.nika.yaml`, fill its value slots, then check it.",
             "The filled lessons below reuse the same workflow logic. Rehearse with `--model mock/echo`; model quality needs a separate evaluation.", "",
             "| Template | Purpose | Filled lesson |", "|---|---|---|"]
    # REUSE-IgnoreEnd
    for name in sorted(names):
        source = (root / "templates" / f"{name}.nika.yaml").read_text()
        title = next((line.split(" · ", 2)[2].rstrip(".") for line in source.splitlines() if line.startswith(f"# TEMPLATE · {name} ·")), name)
        lesson = f"`{examples[name]}`" if name in examples else "—"
        lines.append(f"| `{name}` | {title.replace('|', '/')} | {lesson} |")
    outputs[root / "templates/INDEX.md"] = "\n".join(lines) + "\n"
    outputs[root / "templates/rehearsals.tsv"] = "".join(f"{name}\t{example}\n" for name, example in sorted(examples.items()))
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--write", action="store_true")
    modes.add_argument("--check", action="store_true")
    mode = "--write" if parser.parse_args().write else "--check"
    try:
        outputs = render(ROOT)
    except (ValueError, KeyError, OSError, StopIteration) as exc:
        print(f"template-rehearsals: {exc}", file=sys.stderr)
        return 2
    drift = []
    for path, body in outputs.items():
        if mode == "--write":
            path.write_text(body)
        elif not path.is_file() or path.read_text() != body:
            drift.append(str(path.relative_to(ROOT)))
    if drift:
        print("template-rehearsals: drift: " + ", ".join(drift), file=sys.stderr)
        return 1
    print(f"template-rehearsals: {len(outputs)} projections {mode[2:]} OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
